// ─── Auth Injector ────────────────────────────────────────────────────────────
// Generates NextAuth.js configuration files backed by InsForge auth.
//   individuals → Google + GitHub OAuth
//   teams       → Google + GitHub + org/team scoping in session callback
//   enterprise  → SAML-ready placeholder provider
import type { FileEntry, UserType } from '../types';

// ── Template helpers ──────────────────────────────────────────────────────────

function individualsConfig(): string {
  return `// prodify-layer/auth/[...nextauth].ts
// Generated by Prodify — individuals auth config (Google + GitHub OAuth + InsForge)
import NextAuth from 'next-auth';
import GoogleProvider from 'next-auth/providers/google';
import GitHubProvider from 'next-auth/providers/github';
import { insforge } from '@/lib/insforge';

export const authOptions = {
  secret: process.env.NEXTAUTH_SECRET!,
  providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID!,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET!,
    }),
    GitHubProvider({
      clientId: process.env.GITHUB_CLIENT_ID!,
      clientSecret: process.env.GITHUB_CLIENT_SECRET!,
    }),
  ],
  session: { strategy: 'jwt' as const },
  callbacks: {
    async signIn({ user }: { user: any }) {
      // Upsert user into InsForge on every OAuth sign-in
      await insforge.database
        .from('users')
        .upsert({ email: user.email, name: user.name, image: user.image }, { onConflict: 'email' });
      return true;
    },
    async session({ session, token }: { session: any; token: any }) {
      if (token?.sub) session.user.id = token.sub;
      return session;
    },
  },
};

export default NextAuth(authOptions);
`;
}

function teamsConfig(): string {
  return `// prodify-layer/auth/[...nextauth].ts
// Generated by Prodify — teams auth config (Google + GitHub + org scoping + InsForge)
import NextAuth from 'next-auth';
import GoogleProvider from 'next-auth/providers/google';
import GitHubProvider from 'next-auth/providers/github';
import { insforge } from '@/lib/insforge';

export const authOptions = {
  secret: process.env.NEXTAUTH_SECRET!,
  providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID!,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET!,
    }),
    GitHubProvider({
      clientId: process.env.GITHUB_CLIENT_ID!,
      clientSecret: process.env.GITHUB_CLIENT_SECRET!,
    }),
  ],
  session: { strategy: 'jwt' as const },
  callbacks: {
    async signIn({ user }: { user: any }) {
      await insforge.database
        .from('users')
        .upsert({ email: user.email, name: user.name, image: user.image }, { onConflict: 'email' });
      return true;
    },
    async jwt({ token, user }: { token: any; user: any }) {
      if (user?.id) {
        const { data: membership } = await insforge.database
          .from('memberships')
          .select('organizationId')
          .eq('userId', user.id)
          .single();
        if (membership) token.organizationId = membership.organizationId;
      }
      return token;
    },
    async session({ session, token }: { session: any; token: any }) {
      if (token?.sub) session.user.id = token.sub;
      if (token?.organizationId) session.user.organizationId = token.organizationId;
      return session;
    },
  },
};

export default NextAuth(authOptions);
`;
}

function enterpriseConfig(): string {
  return `// prodify-layer/auth/[...nextauth].ts
// Generated by Prodify — enterprise auth config (SAML-ready + InsForge)
// IMPORTANT: Replace the SAML placeholder with your IdP configuration.
// Recommended provider: BoxyHQ SAML (https://boxyhq.com) or Auth0 Enterprise
import NextAuth from 'next-auth';
import GoogleProvider from 'next-auth/providers/google';
import GitHubProvider from 'next-auth/providers/github';
import { insforge } from '@/lib/insforge';

// TODO: Replace with real SAML/SSO provider
const SAMLProvider = {
  id: 'saml',
  name: 'Enterprise SSO (SAML)',
  type: 'oauth' as const,
  // Configure via BoxyHQ: https://boxyhq.com/docs/jackson/deploy
  authorization: { url: process.env.SAML_AUTHORIZATION_URL! },
  token: { url: process.env.SAML_TOKEN_URL! },
  userinfo: { url: process.env.SAML_USERINFO_URL! },
  clientId: process.env.SAML_CLIENT_ID!,
  clientSecret: process.env.SAML_CLIENT_SECRET!,
  profile(profile: any) {
    return { id: profile.id, name: profile.name, email: profile.email };
  },
};

export const authOptions = {
  secret: process.env.NEXTAUTH_SECRET!,
  providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID!,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET!,
    }),
    GitHubProvider({
      clientId: process.env.GITHUB_CLIENT_ID!,
      clientSecret: process.env.GITHUB_CLIENT_SECRET!,
    }),
    SAMLProvider,
  ],
  session: { strategy: 'jwt' as const },
  callbacks: {
    async signIn({ user }: { user: any }) {
      await insforge.database
        .from('users')
        .upsert({ email: user.email, name: user.name, image: user.image }, { onConflict: 'email' });
      return true;
    },
    async session({ session, token }: { session: any; token: any }) {
      if (token?.sub) session.user.id = token.sub;
      return session;
    },
  },
};

export default NextAuth(authOptions);
`;
}

const routeHandler = `// prodify-layer/routes/api/auth/[...nextauth]/route.ts
// Drop this into app/api/auth/[...nextauth]/route.ts
import NextAuth from 'next-auth';
import { authOptions } from '@/prodify-layer/auth/[...nextauth]';

const handler = NextAuth(authOptions);
export { handler as GET, handler as POST };
`;

function buildNextAuthMiddleware(protectedPaths: string[]): string {
  const pathsJson = JSON.stringify(protectedPaths);
  return `// middleware.ts  ← must live at project root, not in a subdirectory
// Generated by Prodify — session refresh + route protection for NextAuth
import { withAuth } from "next-auth/middleware";

const PROTECTED_PATHS = ${pathsJson};

export default withAuth({
  callbacks: {
    authorized: ({ req, token }) => {
      const isProtected = PROTECTED_PATHS.some(p => req.nextUrl.pathname.startsWith(p));
      if (isProtected && !token) return false;
      return true;
    },
  },
});

export const config = {
  matcher: [
    // Skip Next.js internals, static files, and auth callbacks
    '/((?!_next/static|_next/image|favicon.ico|api/auth|.*\\\\.(?:svg|png|jpg|jpeg|gif|webp)$).*)',
  ],
};
`;
}

// ── Public API ────────────────────────────────────────────────────────────────

const DEFAULT_PROTECTED_PATHS = ['/dashboard', '/account', '/settings', '/billing'];

export function buildAuthFiles(userType: UserType, detectedProtectedPaths?: string[]): FileEntry[] {
  const protectedPaths = detectedProtectedPaths ?? DEFAULT_PROTECTED_PATHS;
  const configContent =
    userType === 'enterprise'
      ? enterpriseConfig()
      : userType === 'teams'
      ? teamsConfig()
      : individualsConfig();

  return [
    {
      relativePath: 'prodify-layer/auth/[...nextauth].ts',
      content: configContent,
    },
    {
      relativePath: 'prodify-layer/routes/api/auth/[...nextauth]/route.ts',
      content: routeHandler,
    },
    {
      relativePath: 'prodify-layer/__middleware_source__.ts',
      content: buildNextAuthMiddleware(protectedPaths),
    },
  ];
}
