import type { FileEntry, PricingModel } from '../types';

function gatewayContent(): string {
  return `// prodify-layer/payments/gateway.ts
// Generated by Prodify — Secure Payment Gateway
import Stripe from 'stripe';
import { createClient } from '@supabase/supabase-js'; // InsForge uses supabase-js client under the hood

export const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: '2024-04-10',
});

// InsForge SDK Client
export const insforge = createClient(
  process.env.NEXT_PUBLIC_INSFORGE_URL!,
  process.env.INSFORGE_SERVICE_ROLE_KEY! // Only use this on the server
);

export async function createCheckout(params: {
  userId: string;
  priceId: string;
  successUrl: string;
  cancelUrl: string;
}): Promise<Stripe.Checkout.Session> {
  // Check if customer exists in subscriptions table
  const { data: sub } = await insforge
    .from('subscriptions')
    .select('stripe_customer_id')
    .eq('user_id', params.userId)
    .single();

  let customerId = sub?.stripe_customer_id;

  if (!customerId) {
    const customer = await stripe.customers.create({ metadata: { userId: params.userId } });
    customerId = customer.id;
    // Store preliminary mapping
    await insforge.from('subscriptions').insert({
      user_id: params.userId,
      stripe_customer_id: customerId,
    });
  }

  return stripe.checkout.sessions.create({
    customer: customerId,
    mode: 'subscription',
    line_items: [{ price: params.priceId, quantity: 1 }],
    success_url: params.successUrl,
    cancel_url: params.cancelUrl,
  });
}
`;
}

function webhookRoute(): string {
  return `// prodify-layer/routes/api/webhooks/stripe/route.ts
// Drop into app/api/webhooks/stripe/route.ts
import { NextResponse } from 'next/server';
import { stripe, insforge } from '@/prodify-layer/payments/gateway';
import Stripe from 'stripe';

export async function POST(req: Request) {
  const body = await req.text();
  const sig = req.headers.get('stripe-signature');
  if (!sig) return NextResponse.json({ error: 'Missing signature' }, { status: 400 });

  let event: Stripe.Event;
  try {
    event = stripe.webhooks.constructEvent(body, sig, process.env.STRIPE_WEBHOOK_SECRET!);
  } catch (err) {
    return NextResponse.json({ error: 'Webhook signature failed' }, { status: 400 });
  }

  // Idempotency check via InsForge
  const { data: existing } = await insforge.from('webhook_events').select('id').eq('stripe_event_id', event.id).single();
  if (existing) return NextResponse.json({ received: true });

  await insforge.from('webhook_events').insert({
    stripe_event_id: event.id,
    type: event.type,
    payload: JSON.parse(JSON.stringify(event))
  });

  // Handle specific events
  if (event.type === 'checkout.session.completed') {
    const session = event.data.object as Stripe.Checkout.Session;
    if (session.subscription) {
      await insforge.from('subscriptions')
        .update({ stripe_subscription_id: session.subscription as string, status: 'active' })
        .eq('stripe_customer_id', session.customer as string);
    }
  }

  return NextResponse.json({ received: true });
}
`;
}

function premiumUiComponent(): string {
  return `// prodify-layer/components/PremiumPricing.tsx
// Drop-in beautiful pricing component using standard modern React
export default function PremiumPricing() {
  return (
    <div style={{ padding: '40px', background: 'linear-gradient(135deg, #0f172a 0%, #1e293b 100%)', color: 'white', borderRadius: '16px', boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)' }}>
      <h2 style={{ fontSize: '2rem', fontWeight: 'bold', marginBottom: '16px' }}>Pro Tier</h2>
      <p style={{ color: '#cbd5e1', marginBottom: '24px' }}>Unlock all SaaS features instantly.</p>
      <button style={{ background: '#3b82f6', color: 'white', padding: '12px 24px', borderRadius: '8px', border: 'none', cursor: 'pointer', fontWeight: 'bold', transition: 'all 0.2s ease' }}>
        Upgrade Now
      </button>
    </div>
  );
}
`;
}

export function buildPaymentsFiles(pricingModel: PricingModel): FileEntry[] {
  return [
    { relativePath: 'prodify-layer/payments/gateway.ts', content: gatewayContent() },
    { relativePath: 'prodify-layer/routes/api/webhooks/stripe/route.ts', content: webhookRoute() },
    { relativePath: 'prodify-layer/components/PremiumPricing.tsx', content: premiumUiComponent() },
  ];
}
