// ─── Payments Injector ────────────────────────────────────────────────────────
// Generates Stripe helpers and API route files based on the pricing model.
//   per-seat → per-unit subscription line items
//   flat     → single flat-rate subscription
//   usage    → metered (usage-based) billing with reportUsage helper
import type { FileEntry, PricingModel } from '../types';

// ── Stripe helper templates ───────────────────────────────────────────────────

function perSeatStripe(): string {
  return `// prodify-layer/payments/stripe.ts
// Generated by Prodify — per-seat Stripe billing helpers
import Stripe from 'stripe';

export const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: '2025-03-31.basil',
});

/** Create a checkout session for per-seat billing */
export async function createPerSeatCheckout(params: {
  customerId: string;
  priceId: string;      // e.g. price_xxx — your per_unit price in Stripe
  quantity: number;     // number of seats
  successUrl: string;
  cancelUrl: string;
}): Promise<Stripe.Checkout.Session> {
  return stripe.checkout.sessions.create({
    customer: params.customerId,
    mode: 'subscription',
    line_items: [
      {
        price: params.priceId,
        quantity: params.quantity,
        adjustable_quantity: { enabled: true, minimum: 1 },
      },
    ],
    success_url: params.successUrl,
    cancel_url: params.cancelUrl,
  });
}
`;
}

function flatStripe(): string {
  return `// prodify-layer/payments/stripe.ts
// Generated by Prodify — flat subscription Stripe billing helpers
import Stripe from 'stripe';

export const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: '2025-03-31.basil',
});

/** Create a checkout session for a flat subscription */
export async function createFlatSubscription(params: {
  customerId: string;
  priceId: string;   // e.g. price_xxx — your flat monthly/annual price in Stripe
  successUrl: string;
  cancelUrl: string;
}): Promise<Stripe.Checkout.Session> {
  return stripe.checkout.sessions.create({
    customer: params.customerId,
    mode: 'subscription',
    line_items: [{ price: params.priceId, quantity: 1 }],
    success_url: params.successUrl,
    cancel_url: params.cancelUrl,
  });
}
`;
}

function usageStripe(): string {
  return `// prodify-layer/payments/stripe.ts
// Generated by Prodify — usage-based (metered) Stripe billing helpers
import Stripe from 'stripe';

export const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: '2025-03-31.basil',
});

/** Create a checkout session for metered (usage-based) billing */
export async function createUsageSubscription(params: {
  customerId: string;
  priceId: string;   // Stripe price with aggregate_usage: 'sum'
  successUrl: string;
  cancelUrl: string;
}): Promise<Stripe.Checkout.Session> {
  return stripe.checkout.sessions.create({
    customer: params.customerId,
    mode: 'subscription',
    line_items: [{ price: params.priceId }],  // no quantity for metered
    success_url: params.successUrl,
    cancel_url: params.cancelUrl,
  });
}

/** Report usage units for a subscription item */
export async function reportUsage(params: {
  subscriptionItemId: string;
  quantity: number;
  timestamp?: number;
}): Promise<Stripe.UsageRecord> {
  return stripe.subscriptionItems.createUsageRecord(
    params.subscriptionItemId,
    {
      quantity: params.quantity,
      timestamp: params.timestamp ?? Math.floor(Date.now() / 1000),
      action: 'increment',
    },
  );
}
`;
}

// ── Shared route templates ────────────────────────────────────────────────────

const checkoutRoute = `// prodify-layer/routes/api/checkout/route.ts
// Drop into app/api/checkout/route.ts
import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/prodify-layer/auth/[...nextauth]';
import { stripe } from '@/prodify-layer/payments/stripe';
import { insforge } from '@/lib/insforge';

export async function POST(req: Request) {
  const session = await getServerSession(authOptions);
  if (!session?.user?.id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const { priceId, quantity } = await req.json() as { priceId: string; quantity?: number };
  // Use request origin so success/cancel URLs work on any domain (local, preview, prod)
  const origin = req.headers.get('origin')
    ?? process.env.NEXT_PUBLIC_APP_URL
    ?? 'http://localhost:3000';

  // Re-use existing Stripe customer to prevent duplicates
  const { data: dbUser } = await insforge.database
    .from('users')
    .select('stripe_customer_id')
    .eq('id', session.user.id)
    .single();

  let customerId = dbUser?.stripe_customer_id as string | null;

  if (!customerId) {
    const customer = await stripe.customers.create({
      email: session.user.email ?? undefined,
      metadata: { user_id: session.user.id },
    });
    customerId = customer.id;
    await insforge.database
      .from('users')
      .update({ stripe_customer_id: customerId })
      .eq('id', session.user.id);
  }

  const checkoutSession = await stripe.checkout.sessions.create({
    customer: customerId,
    mode: 'subscription',
    line_items: [{ price: priceId, quantity: quantity ?? 1 }],
    metadata: { user_id: session.user.id },
    allow_promotion_codes: true,
    success_url: \`\${origin}/dashboard?checkout=success\`,
    cancel_url: \`\${origin}/pricing?checkout=canceled\`,
  });

  if (!checkoutSession.url) {
    return NextResponse.json({ error: 'Failed to create checkout session' }, { status: 500 });
  }

  return NextResponse.json({ url: checkoutSession.url });
}
`;

const webhookRoute = `// prodify-layer/routes/api/webhooks/stripe/route.ts
// Drop into app/api/webhooks/stripe/route.ts
//
// Required Stripe events to enable in your dashboard:
//   checkout.session.completed
//   invoice.payment_succeeded
//   invoice.payment_failed
//   customer.subscription.updated
//   customer.subscription.deleted
//   customer.subscription.trial_will_end
import { NextResponse } from 'next/server';
import { stripe } from '@/prodify-layer/payments/stripe';
import { insforge } from '@/lib/insforge';
import Stripe from 'stripe';

export async function POST(req: Request) {
  const body = await req.text();
  const sig = req.headers.get('stripe-signature');
  if (!sig) {
    return NextResponse.json({ error: 'Missing stripe-signature header' }, { status: 400 });
  }

  let event: Stripe.Event;
  try {
    event = stripe.webhooks.constructEvent(body, sig, process.env.STRIPE_WEBHOOK_SECRET!);
  } catch (err) {
    console.error('[stripe/webhook] signature verification failed:', err);
    return NextResponse.json({ error: 'Webhook signature failed' }, { status: 400 });
  }

  // ── Idempotency: store raw event BEFORE any business logic ─────────────────
  const { error: upsertError } = await insforge.database
    .from('webhook_events')
    .upsert(
      { stripe_event_id: event.id, type: event.type, payload: event },
      { onConflict: 'stripe_event_id' },
    );
  if (upsertError) {
    console.error('[stripe/webhook] failed to store event:', upsertError.message);
    return NextResponse.json({ error: 'Event storage failed' }, { status: 500 });
  }

  try {
    switch (event.type) {
      // ── User completes checkout ─────────────────────────────────────────────
      case 'checkout.session.completed': {
        const session = event.data.object as Stripe.Checkout.Session;
        const userId = session.metadata?.user_id;
        const customerId = session.customer as string | null;
        if (userId && customerId) {
          await insforge.database.from('users').update({
            stripe_customer_id: customerId,
            subscription_tier: 'pro',
            subscription_status: 'active',
          }).eq('id', userId);
        }
        break;
      }

      // ── Recurring payment succeeded — extend access ─────────────────────────
      case 'invoice.payment_succeeded': {
        const invoice = event.data.object as Stripe.Invoice;
        const customerId = invoice.customer as string | null;
        const subscriptionId = invoice.subscription as string | null;
        if (customerId && subscriptionId) {
          const sub = await stripe.subscriptions.retrieve(subscriptionId);
          await insforge.database.from('users').update({
            subscription_status: 'active',
            current_period_end: new Date(sub.current_period_end * 1000).toISOString(),
          }).eq('stripe_customer_id', customerId);
        }
        break;
      }

      // ── Payment failed — mark past_due ──────────────────────────────────────
      case 'invoice.payment_failed': {
        const invoice = event.data.object as Stripe.Invoice;
        const customerId = invoice.customer as string | null;
        if (customerId) {
          await insforge.database.from('users').update({
            subscription_status: 'past_due',
          }).eq('stripe_customer_id', customerId);
          // TODO: trigger dunning email via your email provider
        }
        break;
      }

      // ── Subscription updated — plan change, pause, trial end ────────────────
      case 'customer.subscription.updated': {
        const sub = event.data.object as Stripe.Subscription;
        const customerId = sub.customer as string | null;
        if (customerId) {
          await insforge.database.from('users').update({
            subscription_status: sub.status,
            current_period_end: new Date(sub.current_period_end * 1000).toISOString(),
          }).eq('stripe_customer_id', customerId);
        }
        break;
      }

      // ── Subscription cancelled — downgrade to free ──────────────────────────
      case 'customer.subscription.deleted': {
        const sub = event.data.object as Stripe.Subscription;
        const customerId = sub.customer as string | null;
        if (customerId) {
          await insforge.database.from('users').update({
            subscription_tier: 'free',
            subscription_status: 'canceled',
            current_period_end: null,
          }).eq('stripe_customer_id', customerId);
        }
        break;
      }

      // ── Trial ending in 3 days ──────────────────────────────────────────────
      case 'customer.subscription.trial_will_end': {
        const sub = event.data.object as Stripe.Subscription;
        // TODO: send trial expiry email
        console.log('[stripe/webhook] trial ending for subscription:', sub.id);
        break;
      }

      default:
        break;
    }
  } catch (err) {
    console.error(\`[stripe/webhook] handler error for \${event.type}:\`, err);
    return NextResponse.json({ error: 'Handler error' }, { status: 500 });
  }

  return NextResponse.json({ received: true });
}
`;

const portalRoute = `// prodify-layer/routes/api/billing/portal/route.ts
// Drop into app/api/billing/portal/route.ts — Stripe Customer Portal redirect
// Lets users cancel, update payment method, or change plan without contacting support.
import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/prodify-layer/auth/[...nextauth]';
import { stripe } from '@/prodify-layer/payments/stripe';
import { insforge } from '@/lib/insforge';

export async function POST(req: Request) {
  const session = await getServerSession(authOptions);
  if (!session?.user?.id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const { data: dbUser } = await insforge.database
    .from('users')
    .select('stripe_customer_id')
    .eq('id', session.user.id)
    .single();

  const customerId = dbUser?.stripe_customer_id as string | null;
  if (!customerId) {
    return NextResponse.json(
      { error: 'No billing account found. Please subscribe first.' },
      { status: 400 },
    );
  }

  const origin = req.headers.get('origin')
    ?? process.env.NEXT_PUBLIC_APP_URL
    ?? 'http://localhost:3000';

  const portalSession = await stripe.billingPortal.sessions.create({
    customer: customerId,
    return_url: \`\${origin}/dashboard\`,
  });

  return NextResponse.json({ url: portalSession.url });
}
`;

// ── Public API ────────────────────────────────────────────────────────────────

export function buildPaymentsFiles(pricingModel: PricingModel): FileEntry[] {
  const stripeContent =
    pricingModel === 'usage'
      ? usageStripe()
      : pricingModel === 'flat'
      ? flatStripe()
      : perSeatStripe();

  return [
    { relativePath: 'prodify-layer/payments/stripe.ts', content: stripeContent },
    { relativePath: 'prodify-layer/routes/api/checkout/route.ts', content: checkoutRoute },
    { relativePath: 'prodify-layer/routes/api/webhooks/stripe/route.ts', content: webhookRoute },
    { relativePath: 'prodify-layer/routes/api/billing/portal/route.ts', content: portalRoute },
  ];
}
