// ─── README Injector ──────────────────────────────────────────────────────────
// Generates a README-prodify.md explaining what was injected and how to activate it.
import type { FileEntry, ProdifyAnswers } from '../types';

export function buildReadmeFile(answers: ProdifyAnswers): FileEntry[] {
  const today = new Date().toISOString().split('T')[0];

  const content = `# Prodify Infrastructure Layer

> Auto-generated by [Prodify](https://github.com/maitreyee/prodify) on ${today}

## What was injected

| Layer | Model | Location |
|-------|-------|----------|
| Auth | NextAuth.js (${answers.userType}) | \`prodify-layer/auth/\` |
| Payments | Stripe (${answers.pricingModel}) | \`prodify-layer/payments/\` |
| Database | InsForge (${answers.userType}) | \`prodify-layer/db/\` |
| API Routes | Next.js App Router | \`prodify-layer/routes/api/\` |
| Environment | .env.example | \`.env.example\` |

**Stack detected:** ${answers.stack}
**Pricing model:** ${answers.pricingModel}
**User type:** ${answers.userType}

---

## Activation checklist

- [ ] **Copy .env.example** → \`.env.local\` and fill in all values
- [ ] **Install dependencies:**
  \`\`\`bash
  npm install next-auth @insforge/sdk stripe
  \`\`\`
- [ ] **Run the InsForge schema** — open your InsForge project SQL editor and run:
  \`\`\`bash
  cat prodify-layer/db/schema.sql
  \`\`\`
- [ ] **Copy the InsForge client** into \`lib/insforge.ts\`:
  \`\`\`bash
  cp prodify-layer/db/insforge.ts lib/insforge.ts
  \`\`\`
- [ ] **Mount the API routes** — copy from \`prodify-layer/routes/api/\` into \`app/api/\`
- [ ] **Set up Stripe webhook** (local dev):
  \`\`\`bash
  stripe listen --forward-to localhost:3000/api/webhooks/stripe
  \`\`\`
- [ ] **Configure OAuth apps** — see .env.example for links

---

## File tree

\`\`\`
prodify-layer/
├── auth/
│   └── [...nextauth].ts
├── payments/
│   └── stripe.ts
├── routes/
│   └── api/
│       ├── auth/[...nextauth]/route.ts
│       ├── checkout/route.ts
│       ├── webhooks/stripe/route.ts
│       └── portal/route.ts
├── db/
│   ├── insforge.ts
│   └── schema.sql
└── README-prodify.md
\`\`\`
`;

  return [{ relativePath: 'prodify-layer/README-prodify.md', content }];
}
