// ─── Supabase Injector ────────────────────────────────────────────────────────
// Used when the analysisResult detects Supabase as the existing DB/auth provider.
// Generates @supabase/ssr-based auth helpers, middleware, and SQL migrations
// that extend the repo's existing Supabase project rather than replacing it with InsForge.
import type { FileEntry, UserType } from '../types';

// ── Supabase client helpers ───────────────────────────────────────────────────

const serverClient = `// prodify-layer/supabase/server.ts
// Generated by Prodify — Supabase server client (App Router / Route Handlers)
// Uses @supabase/ssr which handles cookie-based sessions correctly in Next.js 13+
import { createServerClient } from '@supabase/ssr';
import { createClient } from '@supabase/supabase-js';
import { cookies } from 'next/headers';

export async function createSupabaseServerClient() {
  const cookieStore = await cookies();
  return createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll: () => cookieStore.getAll(),
        setAll: (cookiesToSet) => {
          try {
            cookiesToSet.forEach(({ name, value, options }) =>
              cookieStore.set(name, value, options),
            );
          } catch {
            // setAll called from a Server Component — cookies are read-only.
            // Middleware handles the actual refresh, so this is safe to ignore.
          }
        },
      },
    },
  );
}

/**
 * Service-role client — bypasses RLS.
 * ONLY use in trusted server contexts: webhook handlers, admin routes.
 * NEVER expose SUPABASE_SERVICE_ROLE_KEY to the client or prefix it NEXT_PUBLIC_.
 */
export function createSupabaseServiceClient() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { autoRefreshToken: false, persistSession: false } },
  );
}
`;

const browserClient = `// prodify-layer/supabase/client.ts
// Generated by Prodify — Supabase browser client (Client Components only)
import { createBrowserClient } from '@supabase/ssr';

export function createSupabaseBrowserClient() {
  return createBrowserClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
  );
}
`;

// ── Middleware (session refresh + route protection) ───────────────────────────
// NOTE: This file is written to middleware.ts at the PROJECT ROOT, not prodify-layer/.
// Next.js only picks up middleware from the root — placing it anywhere else means
// session protection is silently inert.

function buildMiddleware(protectedPaths: string[]): string {
  const pathsJson = JSON.stringify(protectedPaths);
  return `// middleware.ts  ← must live at project root, not in a subdirectory
// Generated by Prodify — session refresh + route protection for Supabase Auth
// Refreshes the auth session on every request so Server Components always
// get a valid session without an extra round-trip to Supabase.
import { createServerClient } from '@supabase/ssr';
import { NextResponse, type NextRequest } from 'next/server';

// Protected paths detected from this repo's route structure.
// Update this list if you add new authenticated sections.
const PROTECTED_PATHS: string[] = ${pathsJson};

export async function middleware(request: NextRequest) {
  let supabaseResponse = NextResponse.next({ request });

  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll: () => request.cookies.getAll(),
        setAll: (cookiesToSet) => {
          cookiesToSet.forEach(({ name, value }) => request.cookies.set(name, value));
          supabaseResponse = NextResponse.next({ request });
          cookiesToSet.forEach(({ name, value, options }) =>
            supabaseResponse.cookies.set(name, value, options),
          );
        },
      },
    },
  );

  // IMPORTANT: do not remove — prevents logged-out state on SSR
  const { data: { user } } = await supabase.auth.getUser();

  const isProtected = PROTECTED_PATHS.some(p => request.nextUrl.pathname.startsWith(p));
  if (!user && isProtected) {
    const url = request.nextUrl.clone();
    url.pathname = '/login';
    return NextResponse.redirect(url);
  }

  return supabaseResponse;
}

export const config = {
  matcher: [
    // Skip Next.js internals, static files, and auth callbacks
    '/((?!_next/static|_next/image|favicon.ico|api/auth|.*\\.(?:svg|png|jpg|jpeg|gif|webp)$).*)',
  ],
};
`;
}

// ── Auth callback route (OAuth) ───────────────────────────────────────────────

const callbackRoute = `// prodify-layer/routes/api/auth/callback/route.ts
// Drop into app/api/auth/callback/route.ts
// Handles the OAuth redirect from Supabase after social sign-in.
import { createServerClient } from '@supabase/ssr';
import { cookies } from 'next/headers';
import { NextRequest, NextResponse } from 'next/server';

export async function GET(request: NextRequest) {
  const requestUrl = new URL(request.url);
  const code = requestUrl.searchParams.get('code');
  const next = requestUrl.searchParams.get('next') ?? '/dashboard';

  if (code) {
    const cookieStore = await cookies();
    const supabase = createServerClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
      {
        cookies: {
          getAll: () => cookieStore.getAll(),
          setAll: (cookiesToSet) =>
            cookiesToSet.forEach(({ name, value, options }) =>
              cookieStore.set(name, value, options),
            ),
        },
      },
    );

    const { error } = await supabase.auth.exchangeCodeForSession(code);
    if (error) {
      console.error('[auth/callback] exchangeCodeForSession failed:', error.message);
      const url = requestUrl.clone();
      url.pathname = '/login';
      url.searchParams.set('error', 'auth_callback_failed');
      return NextResponse.redirect(url);
    }
  }

  return NextResponse.redirect(new URL(next, request.url));
}
`;

const signoutRoute = `// prodify-layer/routes/api/auth/signout/route.ts
// Drop into app/api/auth/signout/route.ts
import { createSupabaseServerClient } from '@/prodify-layer/supabase/server';
import { NextResponse } from 'next/server';

export async function POST() {
  const supabase = await createSupabaseServerClient();
  const { error } = await supabase.auth.signOut();
  if (error) {
    console.error('[auth/signout] signOut failed:', error.message);
  }
  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? 'http://localhost:3000';
  return NextResponse.redirect(new URL('/login', appUrl));
}
`;

// ── Database schema ───────────────────────────────────────────────────────────

function buildSchema(userType: UserType): string {
  const base = `-- prodify-layer/db/schema.sql
-- Generated by Prodify — Supabase SQL migration
-- Run in your Supabase project: Dashboard → SQL Editor, or via: supabase db push

-- ── Helper: auto-update updated_at on any table ────────────────────────────
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- ── Users (mirror of auth.users with billing fields) ───────────────────────
-- subscription_tier is enforced by CHECK — invalid values fail at DB level, not silently.
CREATE TABLE IF NOT EXISTS public.users (
  id                     UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email                  TEXT UNIQUE NOT NULL,
  full_name              TEXT,
  avatar_url             TEXT,
  stripe_customer_id     TEXT UNIQUE,
  subscription_tier      TEXT NOT NULL DEFAULT 'free'
                           CHECK (subscription_tier IN ('free', 'pro', 'enterprise')),
  subscription_status    TEXT NOT NULL DEFAULT 'inactive'
                           CHECK (subscription_status IN (
                             'active', 'inactive', 'past_due',
                             'canceled', 'trialing', 'paused', 'unpaid'
                           )),
  current_period_end     TIMESTAMPTZ,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS users_stripe_customer_id_idx ON public.users (stripe_customer_id);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "users: own row" ON public.users
  FOR ALL USING (auth.uid() = id);

DROP TRIGGER IF EXISTS users_set_updated_at ON public.users;
CREATE TRIGGER users_set_updated_at
  BEFORE UPDATE ON public.users
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ── Subscriptions (Stripe lifecycle per user) ───────────────────────────────
CREATE TABLE IF NOT EXISTS public.subscriptions (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id                UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  stripe_subscription_id TEXT UNIQUE,
  stripe_price_id        TEXT,
  status                 TEXT NOT NULL DEFAULT 'inactive'
                           CHECK (status IN (
                             'active', 'inactive', 'past_due',
                             'canceled', 'trialing', 'paused', 'unpaid'
                           )),
  current_period_start   TIMESTAMPTZ,
  current_period_end     TIMESTAMPTZ,
  cancel_at              TIMESTAMPTZ,
  canceled_at            TIMESTAMPTZ,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS subscriptions_user_id_idx ON public.subscriptions (user_id);
CREATE INDEX IF NOT EXISTS subscriptions_stripe_sub_id_idx ON public.subscriptions (stripe_subscription_id);

ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "subscriptions: own rows" ON public.subscriptions
  FOR ALL USING (auth.uid() = user_id);

DROP TRIGGER IF EXISTS subscriptions_set_updated_at ON public.subscriptions;
CREATE TRIGGER subscriptions_set_updated_at
  BEFORE UPDATE ON public.subscriptions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ── Webhook events (idempotency store for Stripe events) ────────────────────
-- No public SELECT policy — only accessible via service-role key in webhook handler.
CREATE TABLE IF NOT EXISTS public.webhook_events (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  stripe_event_id TEXT UNIQUE NOT NULL,
  type            TEXT NOT NULL,
  payload         JSONB NOT NULL,
  processed_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS webhook_events_type_idx ON public.webhook_events (type);

ALTER TABLE public.webhook_events ENABLE ROW LEVEL SECURITY;
-- Intentionally no public policy: only service-role can write/read webhook_events.

-- ── Auto-create users row on first sign-in ──────────────────────────────────
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.users (id, email, full_name, avatar_url)
  VALUES (
    NEW.id,
    NEW.email,
    NEW.raw_user_meta_data->>'full_name',
    NEW.raw_user_meta_data->>'avatar_url'
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
`;

  const teamsExtra = `
-- ── Organizations + Memberships (teams / enterprise) ────────────────────────
CREATE TABLE IF NOT EXISTS public.organizations (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name       TEXT NOT NULL,
  slug       TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.memberships (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  role            TEXT NOT NULL DEFAULT 'member'
                    CHECK (role IN ('owner', 'admin', 'member')),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id, organization_id)
);

CREATE INDEX IF NOT EXISTS memberships_user_id_idx ON public.memberships (user_id);
CREATE INDEX IF NOT EXISTS memberships_org_id_idx  ON public.memberships (organization_id);

ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.memberships   ENABLE ROW LEVEL SECURITY;

CREATE POLICY "orgs: members can read" ON public.organizations
  FOR SELECT USING (
    id IN (SELECT organization_id FROM public.memberships WHERE user_id = auth.uid())
  );

CREATE POLICY "memberships: own rows" ON public.memberships
  FOR ALL USING (user_id = auth.uid());

DROP TRIGGER IF EXISTS organizations_set_updated_at ON public.organizations;
CREATE TRIGGER organizations_set_updated_at
  BEFORE UPDATE ON public.organizations
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS memberships_set_updated_at ON public.memberships;
CREATE TRIGGER memberships_set_updated_at
  BEFORE UPDATE ON public.memberships
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
`;

  const enterpriseExtra = teamsExtra + `
-- ── SAML config per org (enterprise only) ───────────────────────────────────
ALTER TABLE public.organizations ADD COLUMN IF NOT EXISTS saml_config JSONB;
`;

  if (userType === 'enterprise') return base + enterpriseExtra;
  if (userType === 'teams') return base + teamsExtra;
  return base;
}

// ── Supabase-aware webhook route ──────────────────────────────────────────────
// Handles all required Stripe lifecycle events. Missing any of these means
// plan changes, failed payments, or cancellations are silently ignored in the DB.

export const supabaseWebhookRoute = `// prodify-layer/routes/api/webhooks/stripe/route.ts
// Drop into app/api/webhooks/stripe/route.ts
// Uses Supabase service-role client to write webhook events + sync subscription status.
//
// Required Stripe events to enable in your dashboard:
//   checkout.session.completed
//   invoice.payment_succeeded
//   invoice.payment_failed
//   customer.subscription.updated
//   customer.subscription.deleted
//   customer.subscription.trial_will_end  (optional — triggers upgrade prompts)
import { NextResponse } from 'next/server';
import Stripe from 'stripe';
import { createSupabaseServiceClient } from '@/prodify-layer/supabase/server';

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, { apiVersion: '2025-03-31.basil' });

export const config = { api: { bodyParser: false } };

export async function POST(req: Request) {
  const body = await req.text();
  const sig = req.headers.get('stripe-signature');
  if (!sig) {
    return NextResponse.json({ error: 'Missing stripe-signature header' }, { status: 400 });
  }

  let event: Stripe.Event;
  try {
    event = stripe.webhooks.constructEvent(body, sig, process.env.STRIPE_WEBHOOK_SECRET!);
  } catch (err) {
    console.error('[stripe/webhook] signature verification failed:', err);
    return NextResponse.json({ error: 'Webhook signature failed' }, { status: 400 });
  }

  const supabase = createSupabaseServiceClient();

  // ── Idempotency: store raw event BEFORE any business logic ─────────────────
  // If the handler crashes after this upsert, re-delivery won't re-process
  // because stripe_event_id is UNIQUE. Safe to re-deliver any event.
  const { error: upsertError } = await supabase
    .from('webhook_events')
    .upsert(
      { stripe_event_id: event.id, type: event.type, payload: event },
      { onConflict: 'stripe_event_id' },
    );
  if (upsertError) {
    console.error('[stripe/webhook] failed to store event:', upsertError.message);
    // Return 500 so Stripe retries — do not silently swallow this
    return NextResponse.json({ error: 'Event storage failed' }, { status: 500 });
  }

  try {
    switch (event.type) {
      // ── User completes checkout ─────────────────────────────────────────────
      case 'checkout.session.completed': {
        const session = event.data.object as Stripe.Checkout.Session;
        const userId = session.metadata?.user_id;
        const customerId = session.customer as string | null;

        if (userId && customerId) {
          await supabase.from('users').update({
            stripe_customer_id: customerId,
            subscription_tier: 'pro',
            subscription_status: 'active',
          }).eq('id', userId);
        }

        // Create subscriptions row if mode is subscription
        if (session.mode === 'subscription' && session.subscription && userId) {
          const sub = await stripe.subscriptions.retrieve(session.subscription as string);
          await supabase.from('subscriptions').upsert({
            user_id: userId,
            stripe_subscription_id: sub.id,
            stripe_price_id: sub.items.data[0]?.price.id ?? null,
            status: sub.status,
            current_period_start: new Date(sub.current_period_start * 1000).toISOString(),
            current_period_end: new Date(sub.current_period_end * 1000).toISOString(),
          }, { onConflict: 'stripe_subscription_id' });
        }
        break;
      }

      // ── Recurring payment succeeded — extend access ─────────────────────────
      case 'invoice.payment_succeeded': {
        const invoice = event.data.object as Stripe.Invoice;
        const customerId = invoice.customer as string | null;
        const subscriptionId = invoice.subscription as string | null;

        if (customerId && subscriptionId) {
          const sub = await stripe.subscriptions.retrieve(subscriptionId);
          await supabase.from('users').update({
            subscription_status: 'active',
            current_period_end: new Date(sub.current_period_end * 1000).toISOString(),
          }).eq('stripe_customer_id', customerId);

          await supabase.from('subscriptions').update({
            status: 'active',
            current_period_start: new Date(sub.current_period_start * 1000).toISOString(),
            current_period_end: new Date(sub.current_period_end * 1000).toISOString(),
          }).eq('stripe_subscription_id', subscriptionId);
        }
        break;
      }

      // ── Payment failed — mark past_due, trigger dunning flow ───────────────
      case 'invoice.payment_failed': {
        const invoice = event.data.object as Stripe.Invoice;
        const customerId = invoice.customer as string | null;
        if (customerId) {
          await supabase.from('users').update({
            subscription_status: 'past_due',
          }).eq('stripe_customer_id', customerId);
          // TODO: send dunning email to prompt card update
        }
        break;
      }

      // ── Subscription updated — plan change, seat change, trial end, pause ──
      case 'customer.subscription.updated': {
        const sub = event.data.object as Stripe.Subscription;
        const customerId = sub.customer as string | null;

        if (customerId) {
          await supabase.from('users').update({
            subscription_status: sub.status,
            current_period_end: new Date(sub.current_period_end * 1000).toISOString(),
          }).eq('stripe_customer_id', customerId);

          await supabase.from('subscriptions').update({
            status: sub.status,
            stripe_price_id: sub.items.data[0]?.price.id ?? null,
            current_period_start: new Date(sub.current_period_start * 1000).toISOString(),
            current_period_end: new Date(sub.current_period_end * 1000).toISOString(),
            cancel_at: sub.cancel_at ? new Date(sub.cancel_at * 1000).toISOString() : null,
          }).eq('stripe_subscription_id', sub.id);
        }
        break;
      }

      // ── Subscription cancelled — downgrade to free ──────────────────────────
      case 'customer.subscription.deleted': {
        const sub = event.data.object as Stripe.Subscription;
        const customerId = sub.customer as string | null;

        if (customerId) {
          await supabase.from('users').update({
            subscription_tier: 'free',
            subscription_status: 'canceled',
            current_period_end: null,
          }).eq('stripe_customer_id', customerId);

          await supabase.from('subscriptions').update({
            status: 'canceled',
            canceled_at: new Date().toISOString(),
          }).eq('stripe_subscription_id', sub.id);
        }
        break;
      }

      // ── Trial ending in 3 days — send upgrade prompt ────────────────────────
      case 'customer.subscription.trial_will_end': {
        const sub = event.data.object as Stripe.Subscription;
        // TODO: send trial expiry email using your email provider
        console.log('[stripe/webhook] trial ending for subscription:', sub.id);
        break;
      }

      default:
        // Unhandled event — safe to ignore, already stored above
        break;
    }
  } catch (err) {
    console.error(\`[stripe/webhook] handler error for \${event.type}:\`, err);
    // Return 500 so Stripe retries the specific event
    return NextResponse.json({ error: 'Handler error' }, { status: 500 });
  }

  return NextResponse.json({ received: true });
}
`;

// ── Supabase-aware checkout route ─────────────────────────────────────────────

export const supabaseCheckoutRoute = `// prodify-layer/routes/api/checkout/route.ts
// Drop into app/api/checkout/route.ts
import { NextResponse } from 'next/server';
import Stripe from 'stripe';
import { createSupabaseServerClient } from '@/prodify-layer/supabase/server';

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, { apiVersion: '2025-03-31.basil' });

export async function POST(req: Request) {
  const supabase = await createSupabaseServerClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const { priceId } = await req.json() as { priceId: string };
  // Use request origin as base URL so success/cancel URLs work on any domain
  const origin = req.headers.get('origin')
    ?? process.env.NEXT_PUBLIC_APP_URL
    ?? 'http://localhost:3000';

  // Re-use existing Stripe customer to prevent duplicates
  const { data: dbUser } = await supabase
    .from('users')
    .select('stripe_customer_id')
    .eq('id', user.id)
    .single();

  let customerId = dbUser?.stripe_customer_id as string | null;

  if (!customerId) {
    const customer = await stripe.customers.create({
      email: user.email,
      metadata: { user_id: user.id },
    });
    customerId = customer.id;
    await supabase.from('users').update({ stripe_customer_id: customerId }).eq('id', user.id);
  }

  const session = await stripe.checkout.sessions.create({
    customer: customerId,
    mode: 'subscription',
    line_items: [{ price: priceId, quantity: 1 }],
    metadata: { user_id: user.id },
    allow_promotion_codes: true,
    success_url: \`\${origin}/dashboard?checkout=success\`,
    cancel_url: \`\${origin}/pricing?checkout=canceled\`,
  });

  if (!session.url) {
    return NextResponse.json({ error: 'Failed to create checkout session' }, { status: 500 });
  }

  return NextResponse.json({ url: session.url });
}
`;

// ── Customer portal route ─────────────────────────────────────────────────────
// Without this, users cannot cancel or update their payment method.
// Chargebacks and legal risk (GDPR, California) require a self-serve cancel path.

export const supabasePortalRoute = `// prodify-layer/routes/api/billing/portal/route.ts
// Drop into app/api/billing/portal/route.ts
// Redirects the authenticated user to the Stripe Customer Portal
// where they can cancel, update payment method, or change plan.
import { NextResponse } from 'next/server';
import Stripe from 'stripe';
import { createSupabaseServerClient } from '@/prodify-layer/supabase/server';

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, { apiVersion: '2025-03-31.basil' });

export async function POST(req: Request) {
  const supabase = await createSupabaseServerClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const { data: dbUser } = await supabase
    .from('users')
    .select('stripe_customer_id')
    .eq('id', user.id)
    .single();

  const customerId = dbUser?.stripe_customer_id as string | null;
  if (!customerId) {
    return NextResponse.json(
      { error: 'No billing account found. Please subscribe first.' },
      { status: 400 },
    );
  }

  const origin = req.headers.get('origin')
    ?? process.env.NEXT_PUBLIC_APP_URL
    ?? 'http://localhost:3000';

  const portalSession = await stripe.billingPortal.sessions.create({
    customer: customerId,
    return_url: \`\${origin}/dashboard\`,
  });

  return NextResponse.json({ url: portalSession.url });
}
`;

// ── .env.example additions ────────────────────────────────────────────────────

export const supabaseEnvExample = `# ── Supabase ─────────────────────────────────────────────────────────────────
# Find these in: Supabase Dashboard → Project Settings → API
NEXT_PUBLIC_SUPABASE_URL=https://your-project-ref.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=your-anon-key-here
# WARNING: Never expose this key client-side or prefix it NEXT_PUBLIC_
SUPABASE_SERVICE_ROLE_KEY=your-service-role-key-here

# ── Stripe ────────────────────────────────────────────────────────────────────
# Find these in: Stripe Dashboard → Developers → API keys
STRIPE_SECRET_KEY=sk_test_...
STRIPE_WEBHOOK_SECRET=whsec_...
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_...

# ── App ───────────────────────────────────────────────────────────────────────
# Used for Stripe checkout success/cancel URLs. Set to your production URL on deploy.
NEXT_PUBLIC_APP_URL=http://localhost:3000
`;

// ── package.json additions ────────────────────────────────────────────────────

export const supabaseRequiredDeps: Record<string, string> = {
  '@supabase/ssr': '^0.6.1',
  '@supabase/supabase-js': '^2.49.4',
  'stripe': '^17.7.0',
};

// ── Public API ────────────────────────────────────────────────────────────────

// Default protected paths used when repo route scanning is unavailable.
// The inject route should override this with paths detected from the actual repo.
const DEFAULT_PROTECTED_PATHS = ['/dashboard', '/account', '/settings', '/billing'];

export function buildSupabaseAuthFiles(
  userType: UserType,
  detectedProtectedPaths?: string[],
): FileEntry[] {
  const protectedPaths = detectedProtectedPaths ?? DEFAULT_PROTECTED_PATHS;
  return [
    { relativePath: 'prodify-layer/supabase/server.ts', content: serverClient },
    { relativePath: 'prodify-layer/supabase/client.ts', content: browserClient },
    // NOTE: middleware.ts is intentionally written to the project root by the inject route.
    // The path here is used as a marker only — the inject route rewrites the destination.
    { relativePath: 'prodify-layer/__middleware_source__.ts', content: buildMiddleware(protectedPaths) },
    { relativePath: 'prodify-layer/routes/api/auth/callback/route.ts', content: callbackRoute },
    { relativePath: 'prodify-layer/routes/api/auth/signout/route.ts', content: signoutRoute },
  ];
}

export function buildSupabaseDbFiles(userType: UserType): FileEntry[] {
  return [
    { relativePath: 'prodify-layer/db/schema.sql', content: buildSchema(userType) },
  ];
}

export function buildSupabasePaymentsFiles(): FileEntry[] {
  return [
    { relativePath: 'prodify-layer/routes/api/checkout/route.ts', content: supabaseCheckoutRoute },
    { relativePath: 'prodify-layer/routes/api/webhooks/stripe/route.ts', content: supabaseWebhookRoute },
    { relativePath: 'prodify-layer/routes/api/billing/portal/route.ts', content: supabasePortalRoute },
  ];
}
