// ─── Supabase Injector ────────────────────────────────────────────────────────
// Used when the analysisResult detects Supabase as the existing DB/auth provider.
// Generates @supabase/ssr-based auth helpers, middleware, and SQL migrations
// that extend the repo's existing Supabase project rather than replacing it with InsForge.
import type { FileEntry, UserType } from '../types';

// ── Supabase client helpers ───────────────────────────────────────────────────

const serverClient = `// prodify-layer/supabase/server.ts
// Generated by Prodify — Supabase server client (App Router / Route Handlers)
// Uses @supabase/ssr which handles cookie-based sessions correctly in Next.js 13+
import { createServerClient } from '@supabase/ssr';
import { cookies } from 'next/headers';

export async function createSupabaseServerClient() {
  const cookieStore = await cookies();
  return createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll: () => cookieStore.getAll(),
        setAll: (cookiesToSet) => {
          try {
            cookiesToSet.forEach(({ name, value, options }) =>
              cookieStore.set(name, value, options),
            );
          } catch {
            // setAll called from a Server Component — cookies are read-only.
            // Middleware handles the actual refresh, so this is safe to ignore.
          }
        },
      },
    },
  );
}

/** Service-role client — only use in trusted server contexts (webhooks, admin routes) */
export function createSupabaseServiceClient() {
  const { createClient } = require('@supabase/supabase-js');
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { autoRefreshToken: false, persistSession: false } },
  );
}
`;

const browserClient = `// prodify-layer/supabase/client.ts
// Generated by Prodify — Supabase browser client (Client Components)
import { createBrowserClient } from '@supabase/ssr';

export function createSupabaseBrowserClient() {
  return createBrowserClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
  );
}
`;

// ── Middleware (session refresh + route protection) ───────────────────────────

const middleware = `// prodify-layer/middleware.ts
// Generated by Prodify — session refresh middleware for Supabase Auth
// Drop this into middleware.ts at your project root.
// It refreshes the auth session on every request so Server Components always
// get a valid session without an extra round-trip to Supabase.
import { createServerClient } from '@supabase/ssr';
import { NextResponse, type NextRequest } from 'next/server';

export async function middleware(request: NextRequest) {
  let supabaseResponse = NextResponse.next({ request });

  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll: () => request.cookies.getAll(),
        setAll: (cookiesToSet) => {
          cookiesToSet.forEach(({ name, value }) => request.cookies.set(name, value));
          supabaseResponse = NextResponse.next({ request });
          cookiesToSet.forEach(({ name, value, options }) =>
            supabaseResponse.cookies.set(name, value, options),
          );
        },
      },
    },
  );

  // Refresh session — IMPORTANT: do not remove, prevents logged-out state on SSR
  const { data: { user } } = await supabase.auth.getUser();

  // Redirect unauthenticated users away from protected routes
  // TODO: adjust this list to match your protected paths
  const protectedPaths = ['/dashboard', '/analyze', '/report', '/recommendations'];
  const isProtected = protectedPaths.some(p => request.nextUrl.pathname.startsWith(p));

  if (!user && isProtected) {
    const url = request.nextUrl.clone();
    url.pathname = '/login';
    return NextResponse.redirect(url);
  }

  return supabaseResponse;
}

export const config = {
  matcher: [
    // Skip Next.js internals and static files
    '/((?!_next/static|_next/image|favicon.ico|.*\\.(?:svg|png|jpg|jpeg|gif|webp)$).*)',
  ],
};
`;

// ── Auth callback route (OAuth) ───────────────────────────────────────────────

const callbackRoute = `// prodify-layer/routes/api/auth/callback/route.ts
// Drop into app/api/auth/callback/route.ts
// Handles the OAuth redirect from Supabase after social sign-in.
import { createServerClient } from '@supabase/ssr';
import { cookies } from 'next/headers';
import { NextRequest, NextResponse } from 'next/server';

export async function GET(request: NextRequest) {
  const requestUrl = new URL(request.url);
  const code = requestUrl.searchParams.get('code');
  const next = requestUrl.searchParams.get('next') ?? '/dashboard';

  if (code) {
    const cookieStore = await cookies();
    const supabase = createServerClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
      {
        cookies: {
          getAll: () => cookieStore.getAll(),
          setAll: (cookiesToSet) =>
            cookiesToSet.forEach(({ name, value, options }) =>
              cookieStore.set(name, value, options),
            ),
        },
      },
    );
    await supabase.auth.exchangeCodeForSession(code);
  }

  return NextResponse.redirect(new URL(next, request.url));
}
`;

const signoutRoute = `// prodify-layer/routes/api/auth/signout/route.ts
// Drop into app/api/auth/signout/route.ts
import { createSupabaseServerClient } from '@/prodify-layer/supabase/server';
import { NextResponse } from 'next/server';

export async function POST() {
  const supabase = await createSupabaseServerClient();
  await supabase.auth.signOut();
  return NextResponse.redirect(new URL('/login', process.env.NEXT_PUBLIC_APP_URL ?? 'http://localhost:3000'));
}
`;

// ── Database schema ───────────────────────────────────────────────────────────

function buildSchema(userType: UserType): string {
  const base = `-- prodify-layer/db/schema.sql
-- Generated by Prodify — Supabase SQL migration
-- Run in your Supabase project: Dashboard → SQL Editor, or via supabase db push

-- Users mirror auth.users; extended with Stripe and subscription fields
CREATE TABLE IF NOT EXISTS public.users (
  id                     UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email                  TEXT UNIQUE NOT NULL,
  full_name              TEXT,
  avatar_url             TEXT,
  stripe_customer_id     TEXT UNIQUE,
  subscription_tier      TEXT NOT NULL DEFAULT 'free',   -- 'free' | 'pro' | 'enterprise'
  subscription_status    TEXT NOT NULL DEFAULT 'inactive', -- Stripe status
  current_period_end     TIMESTAMPTZ,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Row-level security: users can only read/update their own row
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "users: own row" ON public.users
  FOR ALL USING (auth.uid() = id);

-- Subscriptions: tracks Stripe subscription lifecycle per user
CREATE TABLE IF NOT EXISTS public.subscriptions (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id                UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  stripe_subscription_id TEXT UNIQUE,
  stripe_price_id        TEXT,
  status                 TEXT NOT NULL DEFAULT 'inactive',
  current_period_start   TIMESTAMPTZ,
  current_period_end     TIMESTAMPTZ,
  cancel_at              TIMESTAMPTZ,
  canceled_at            TIMESTAMPTZ,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "subscriptions: own rows" ON public.subscriptions
  FOR ALL USING (auth.uid() = user_id);

-- Webhook events: idempotency store for Stripe events
CREATE TABLE IF NOT EXISTS public.webhook_events (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  stripe_event_id TEXT UNIQUE NOT NULL,
  type            TEXT NOT NULL,
  payload         JSONB NOT NULL,
  processed_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- webhook_events is service-role only — no RLS policy for public
ALTER TABLE public.webhook_events ENABLE ROW LEVEL SECURITY;

-- Auto-create users row on first sign-in via Supabase trigger
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.users (id, email, full_name, avatar_url)
  VALUES (
    NEW.id,
    NEW.email,
    NEW.raw_user_meta_data->>'full_name',
    NEW.raw_user_meta_data->>'avatar_url'
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
`;

  const teamsExtra = `
-- Organizations and memberships (teams / enterprise only)
CREATE TABLE IF NOT EXISTS public.organizations (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name       TEXT NOT NULL,
  slug       TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.memberships (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  role            TEXT NOT NULL DEFAULT 'member',  -- 'owner' | 'admin' | 'member'
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id, organization_id)
);

ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.memberships ENABLE ROW LEVEL SECURITY;

CREATE POLICY "orgs: members can read" ON public.organizations
  FOR SELECT USING (
    id IN (SELECT organization_id FROM public.memberships WHERE user_id = auth.uid())
  );

CREATE POLICY "memberships: own rows" ON public.memberships
  FOR ALL USING (user_id = auth.uid());
`;

  const enterpriseExtra = teamsExtra + `
-- SAML config per org (enterprise only)
ALTER TABLE public.organizations ADD COLUMN IF NOT EXISTS saml_config JSONB;
`;

  if (userType === 'enterprise') return base + enterpriseExtra;
  if (userType === 'teams') return base + teamsExtra;
  return base;
}

// ── Supabase-aware webhook route (uses supabase service client, not InsForge) ─

export const supabaseWebhookRoute = `// prodify-layer/routes/api/webhooks/stripe/route.ts
// Drop into app/api/webhooks/stripe/route.ts
// Uses Supabase service-role client to write webhook events + sync subscription status.
import { NextResponse } from 'next/server';
import Stripe from 'stripe';
import { createSupabaseServiceClient } from '@/prodify-layer/supabase/server';

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, { apiVersion: '2024-04-10' });

export async function POST(req: Request) {
  const body = await req.text();
  const sig = req.headers.get('stripe-signature');
  if (!sig) return NextResponse.json({ error: 'Missing stripe-signature' }, { status: 400 });

  let event: Stripe.Event;
  try {
    event = stripe.webhooks.constructEvent(body, sig, process.env.STRIPE_WEBHOOK_SECRET!);
  } catch {
    return NextResponse.json({ error: 'Webhook signature failed' }, { status: 400 });
  }

  const supabase = createSupabaseServiceClient();

  // Idempotency store
  await supabase.from('webhook_events').upsert(
    { stripe_event_id: event.id, type: event.type, payload: event },
    { onConflict: 'stripe_event_id' },
  );

  switch (event.type) {
    case 'checkout.session.completed': {
      const session = event.data.object as Stripe.Checkout.Session;
      const userId = session.metadata?.user_id;
      if (userId && session.customer) {
        await supabase.from('users').update({
          stripe_customer_id: session.customer as string,
          subscription_tier: 'pro',
          subscription_status: 'active',
        }).eq('id', userId);
      }
      break;
    }
    case 'invoice.payment_succeeded': {
      const invoice = event.data.object as Stripe.Invoice;
      if (invoice.customer) {
        await supabase.from('users').update({
          subscription_status: 'active',
          current_period_end: new Date((invoice as any).period_end * 1000).toISOString(),
        }).eq('stripe_customer_id', invoice.customer as string);
      }
      break;
    }
    case 'customer.subscription.deleted': {
      const sub = event.data.object as Stripe.Subscription;
      if (sub.customer) {
        await supabase.from('users').update({
          subscription_tier: 'free',
          subscription_status: 'canceled',
        }).eq('stripe_customer_id', sub.customer as string);
      }
      break;
    }
  }

  return NextResponse.json({ received: true });
}
`;

// ── Supabase-aware checkout route ─────────────────────────────────────────────

export const supabaseCheckoutRoute = `// prodify-layer/routes/api/checkout/route.ts
// Drop into app/api/checkout/route.ts
// Reads the authenticated user from Supabase session, looks up Stripe customer ID,
// then creates a Checkout session.
import { NextResponse } from 'next/server';
import Stripe from 'stripe';
import { createSupabaseServerClient } from '@/prodify-layer/supabase/server';

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, { apiVersion: '2024-04-10' });

export async function POST(req: Request) {
  const supabase = await createSupabaseServerClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const { priceId } = await req.json() as { priceId: string };
  const origin = process.env.NEXT_PUBLIC_APP_URL ?? 'http://localhost:3000';

  // Look up existing Stripe customer or create one
  const { data: dbUser } = await supabase.from('users').select('stripe_customer_id').eq('id', user.id).single();
  let customerId = dbUser?.stripe_customer_id as string | undefined;

  if (!customerId) {
    const customer = await stripe.customers.create({
      email: user.email,
      metadata: { user_id: user.id },
    });
    customerId = customer.id;
    await supabase.from('users').update({ stripe_customer_id: customerId }).eq('id', user.id);
  }

  const session = await stripe.checkout.sessions.create({
    customer: customerId,
    mode: 'subscription',
    line_items: [{ price: priceId, quantity: 1 }],
    metadata: { user_id: user.id },
    success_url: \`\${origin}/dashboard?success=1\`,
    cancel_url: \`\${origin}/pricing?canceled=1\`,
  });

  return NextResponse.json({ url: session.url });
}
`;

// ── Public API ────────────────────────────────────────────────────────────────

export function buildSupabaseAuthFiles(userType: UserType): FileEntry[] {
  return [
    { relativePath: 'prodify-layer/supabase/server.ts', content: serverClient },
    { relativePath: 'prodify-layer/supabase/client.ts', content: browserClient },
    { relativePath: 'prodify-layer/middleware.ts', content: middleware },
    { relativePath: 'prodify-layer/routes/api/auth/callback/route.ts', content: callbackRoute },
    { relativePath: 'prodify-layer/routes/api/auth/signout/route.ts', content: signoutRoute },
  ];
}

export function buildSupabaseDbFiles(userType: UserType): FileEntry[] {
  return [
    { relativePath: 'prodify-layer/db/schema.sql', content: buildSchema(userType) },
  ];
}

export function buildSupabasePaymentsFiles(): FileEntry[] {
  return [
    { relativePath: 'prodify-layer/routes/api/checkout/route.ts', content: supabaseCheckoutRoute },
    { relativePath: 'prodify-layer/routes/api/webhooks/stripe/route.ts', content: supabaseWebhookRoute },
  ];
}
