// ─── Auth Injector ────────────────────────────────────────────────────────────
// Generates NextAuth.js configuration files based on user type.
//   individuals → Google + GitHub OAuth
//   teams       → Google + GitHub + org/team scoping in session callback
//   enterprise  → SAML-ready placeholder provider
import type { FileEntry, UserType } from '../types';

// ── Template helpers ──────────────────────────────────────────────────────────

function individualsConfig(): string {
  return `// prodify-layer/auth/[...nextauth].ts
// Generated by Prodify — individuals auth config (Google + GitHub OAuth)
import NextAuth from 'next-auth';
import GoogleProvider from 'next-auth/providers/google';
import GitHubProvider from 'next-auth/providers/github';
import { PrismaAdapter } from '@auth/prisma-adapter';
import { prisma } from '@/lib/prisma';

export const authOptions = {
  adapter: PrismaAdapter(prisma),
  providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID!,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET!,
    }),
    GitHubProvider({
      clientId: process.env.GITHUB_CLIENT_ID!,
      clientSecret: process.env.GITHUB_CLIENT_SECRET!,
    }),
  ],
  session: { strategy: 'jwt' as const },
  callbacks: {
    async session({ session, token }: { session: any; token: any }) {
      if (token?.sub) session.user.id = token.sub;
      return session;
    },
  },
};

export default NextAuth(authOptions);
`;
}

function teamsConfig(): string {
  return `// prodify-layer/auth/[...nextauth].ts
// Generated by Prodify — teams auth config (Google + GitHub + org scoping)
import NextAuth from 'next-auth';
import GoogleProvider from 'next-auth/providers/google';
import GitHubProvider from 'next-auth/providers/github';
import { PrismaAdapter } from '@auth/prisma-adapter';
import { prisma } from '@/lib/prisma';

export const authOptions = {
  adapter: PrismaAdapter(prisma),
  providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID!,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET!,
    }),
    GitHubProvider({
      clientId: process.env.GITHUB_CLIENT_ID!,
      clientSecret: process.env.GITHUB_CLIENT_SECRET!,
    }),
  ],
  session: { strategy: 'jwt' as const },
  callbacks: {
    async session({ session, token }: { session: any; token: any }) {
      if (token?.sub) session.user.id = token.sub;
      // Attach organizationId from DB membership
      const membership = await prisma.membership.findFirst({
        where: { userId: token.sub as string },
        select: { organizationId: true },
      });
      if (membership) session.user.organizationId = membership.organizationId;
      return session;
    },
  },
};

export default NextAuth(authOptions);
`;
}

function enterpriseConfig(): string {
  return `// prodify-layer/auth/[...nextauth].ts
// Generated by Prodify — enterprise auth config (SAML-ready placeholder)
// IMPORTANT: Replace the SAML placeholder with your IdP configuration.
// Recommended provider: BoxyHQ SAML (https://boxyhq.com) or Auth0 Enterprise
import NextAuth from 'next-auth';
import GoogleProvider from 'next-auth/providers/google';
import GitHubProvider from 'next-auth/providers/github';
import { PrismaAdapter } from '@auth/prisma-adapter';
import { prisma } from '@/lib/prisma';

// TODO: Replace with real SAML/SSO provider
const SAMLProvider = {
  id: 'saml',
  name: 'Enterprise SSO (SAML)',
  type: 'oauth' as const,
  // Configure via BoxyHQ: https://boxyhq.com/docs/jackson/deploy
  authorization: { url: process.env.SAML_AUTHORIZATION_URL! },
  token: { url: process.env.SAML_TOKEN_URL! },
  userinfo: { url: process.env.SAML_USERINFO_URL! },
  clientId: process.env.SAML_CLIENT_ID!,
  clientSecret: process.env.SAML_CLIENT_SECRET!,
  profile(profile: any) {
    return { id: profile.id, name: profile.name, email: profile.email };
  },
};

export const authOptions = {
  adapter: PrismaAdapter(prisma),
  providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID!,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET!,
    }),
    GitHubProvider({
      clientId: process.env.GITHUB_CLIENT_ID!,
      clientSecret: process.env.GITHUB_CLIENT_SECRET!,
    }),
    SAMLProvider,
  ],
  session: { strategy: 'jwt' as const },
  callbacks: {
    async session({ session, token }: { session: any; token: any }) {
      if (token?.sub) session.user.id = token.sub;
      return session;
    },
  },
};

export default NextAuth(authOptions);
`;
}

const routeHandler = `// prodify-layer/routes/api/auth/[...nextauth]/route.ts
// Drop this into app/api/auth/[...nextauth]/route.ts
import NextAuth from 'next-auth';
import { authOptions } from '@/prodify-layer/auth/[...nextauth]';

const handler = NextAuth(authOptions);
export { handler as GET, handler as POST };
`;

// ── Public API ────────────────────────────────────────────────────────────────

export function buildAuthFiles(userType: UserType): FileEntry[] {
  const configContent =
    userType === 'enterprise'
      ? enterpriseConfig()
      : userType === 'teams'
      ? teamsConfig()
      : individualsConfig();

  return [
    {
      relativePath: 'prodify-layer/auth/[...nextauth].ts',
      content: configContent,
    },
    {
      relativePath: 'prodify-layer/routes/api/auth/[...nextauth]/route.ts',
      content: routeHandler,
    },
  ];
}
