// ─── CI Injector ──────────────────────────────────────────────────────────────
// Generates a .github/workflows/deploy.yml tailored to the chosen deploy target.
//   vercel   → Vercel CLI deployment with pull/build/deploy steps
//   railway  → Railway CLI deployment
//   fly      → Fly.io deployment via flyctl
//   aws      → AWS Lightsail container push
//   none     → Build-only CI check (no deploy step)
import type { FileEntry, DeployTarget } from '../types';

function vercelWorkflow(): string {
  return `# Generated by Prodify — Vercel deployment workflow
# Required GitHub Secrets:
#   VERCEL_TOKEN, VERCEL_ORG_ID, VERCEL_PROJECT_ID
# Run: vercel link in your project root to get org/project IDs
name: Deploy to Vercel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel environment
        run: vercel pull --yes --environment=\${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }} --token=\${{ secrets.VERCEL_TOKEN }}

      - name: Build project artifacts
        run: vercel build \${{ github.ref == 'refs/heads/main' && '--prod' || '' }} --token=\${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: vercel deploy --prebuilt \${{ github.ref == 'refs/heads/main' && '--prod' || '' }} --token=\${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: \${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: \${{ secrets.VERCEL_PROJECT_ID }}
`;
}

function railwayWorkflow(): string {
  return `# Generated by Prodify — Railway deployment workflow
# Required GitHub Secrets: RAILWAY_TOKEN
name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run type check
        run: npx tsc --noEmit

      - name: Install Railway CLI
        run: npm install --global @railway/cli

      - name: Deploy to Railway
        run: railway up --service=production
        env:
          RAILWAY_TOKEN: \${{ secrets.RAILWAY_TOKEN }}
`;
}

function flyWorkflow(): string {
  return `# Generated by Prodify — Fly.io deployment workflow
# Required GitHub Secrets: FLY_API_TOKEN
# Assumes a fly.toml exists in the repo root (run: fly launch to generate one)
name: Deploy to Fly.io

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Deploy to Fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Run flyctl deploy
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: \${{ secrets.FLY_API_TOKEN }}
`;
}

function awsWorkflow(): string {
  return `# Generated by Prodify — AWS Lightsail deployment workflow
# Required GitHub Secrets: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION
# Assumes Docker image is built and pushed to Lightsail container registry.
name: Deploy to AWS Lightsail

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: \${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: \${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: \${{ secrets.AWS_REGION }}

      - name: Build Docker image
        run: docker build -t app:latest .

      - name: Push to Lightsail container service
        run: |
          aws lightsail push-container-image \\
            --region \${{ secrets.AWS_REGION }} \\
            --service-name your-service-name \\
            --label app \\
            --image app:latest
          # TODO: replace 'your-service-name' with your Lightsail service name
`;
}

function noneWorkflow(): string {
  return `# Generated by Prodify — Build and type check CI (no deploy step)
# Add a deploy job when you choose a deployment target.
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npx tsc --noEmit

      - name: Build
        run: npm run build
`;
}

// ── Public API ────────────────────────────────────────────────────────────────

export function buildCiFiles(deployTarget: DeployTarget): FileEntry[] {
  const content =
    deployTarget === 'vercel'   ? vercelWorkflow()  :
    deployTarget === 'railway'  ? railwayWorkflow() :
    deployTarget === 'fly'      ? flyWorkflow()     :
    deployTarget === 'aws'      ? awsWorkflow()     :
                                  noneWorkflow();

  return [
    { relativePath: '.github/workflows/deploy.yml', content },
  ];
}
