// ─── Compliance Injector ──────────────────────────────────────────────────────
// Generates compliance templates based on the chosen region:
//   eu-gdpr  → GDPR cookie consent banner (React component) + privacy policy template
//   us       → CCPA notice template
//   global   → Minimal terms of service template
import type { FileEntry, ComplianceRegion, ProdifyAnswers } from '../types';

function cookieBanner(appName: string): string {
  return `// prodify-layer/compliance/cookie-banner.tsx
// Generated by Prodify — GDPR Cookie Consent Banner
// Mount this in your root layout.tsx. Stores consent in localStorage.
'use client';

import { useState, useEffect } from 'react';

export function CookieBanner() {
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    const consent = localStorage.getItem('cookie-consent');
    if (!consent) setVisible(true);
  }, []);

  if (!visible) return null;

  function accept() {
    localStorage.setItem('cookie-consent', 'accepted');
    setVisible(false);
    // TODO: enable analytics, tracking scripts after consent
  }

  function decline() {
    localStorage.setItem('cookie-consent', 'declined');
    setVisible(false);
    // TODO: keep analytics off, only use strictly necessary cookies
  }

  return (
    <div
      style={{
        position: 'fixed',
        bottom: 0,
        left: 0,
        right: 0,
        padding: '16px 24px',
        background: '#1a1b2e',
        borderTop: '1px solid #323779',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: '16px',
        zIndex: 9999,
      }}
    >
      <p style={{ color: '#e3f4f8', fontSize: '14px', margin: 0 }}>
        ${appName} uses cookies to improve your experience and analyze usage.{' '}
        <a href="/privacy" style={{ color: '#00d7ff' }}>Privacy Policy</a>
      </p>
      <div style={{ display: 'flex', gap: '8px', flexShrink: 0 }}>
        <button
          onClick={decline}
          style={{
            padding: '8px 16px',
            border: '1px solid #323779',
            borderRadius: '8px',
            background: 'transparent',
            color: '#8589b2',
            cursor: 'pointer',
            fontSize: '13px',
          }}
        >
          Decline
        </button>
        <button
          onClick={accept}
          style={{
            padding: '8px 16px',
            border: 'none',
            borderRadius: '8px',
            background: '#575efe',
            color: '#fff',
            cursor: 'pointer',
            fontSize: '13px',
            fontWeight: '600',
          }}
        >
          Accept all
        </button>
      </div>
    </div>
  );
}
`;
}

function privacyPolicy(appName: string): string {
  return `# Privacy Policy — ${appName}

> **Last updated:** ${new Date().toISOString().split('T')[0]}
> **Generated by Prodify — replace all [PLACEHOLDERS] before publishing.**

## 1. Who we are

${appName} ("we", "us", "our") is operated by [Your Company Name], registered at [Your Address].
Data controller contact: [privacy@yourdomain.com]

## 2. What data we collect

| Data | Purpose | Legal basis |
|---|---|---|
| Email address | Account creation and communication | Contract performance |
| Name | Personalisation | Contract performance |
| Usage data (pages, actions) | Product analytics | Legitimate interest |
| Payment data | Billing (processed by Stripe — we never store card numbers) | Contract performance |
| IP address, browser info | Security, fraud prevention | Legitimate interest |

## 3. Your rights under GDPR (EU users)

You have the right to:
- **Access** — request a copy of your personal data
- **Rectification** — correct inaccurate data
- **Erasure** — request deletion of your data ("right to be forgotten")
- **Portability** — receive your data in a machine-readable format
- **Objection** — object to processing based on legitimate interest
- **Restriction** — request we limit how we use your data

To exercise these rights, email [privacy@yourdomain.com]. We will respond within 30 days.

## 4. Data retention

We retain your data for as long as your account is active, plus [12] months after deletion, unless longer retention is required by law.

## 5. Third-party services

| Service | Purpose | Privacy policy |
|---|---|---|
| Stripe | Payment processing | https://stripe.com/privacy |
| Resend | Transactional email | https://resend.com/legal/privacy-policy |
| [Your database host] | Data storage | [Link] |

## 6. Cookies

We use strictly necessary cookies (session, auth) and, with your consent, analytics cookies.
See our [Cookie Policy](/cookies) for details.

## 7. Transfers outside the EU

If we transfer your data outside the EEA, we ensure adequate protection via [Standard Contractual Clauses / adequacy decision].

## 8. How to complain

If you're unhappy with how we handle your data, contact [privacy@yourdomain.com] or lodge a complaint with your national data protection authority.
`;
}

function ccpaNotice(appName: string): string {
  return `# CCPA Privacy Notice — ${appName}

> **Last updated:** ${new Date().toISOString().split('T')[0]}
> **Generated by Prodify — replace all [PLACEHOLDERS] before publishing.**

This notice applies to California residents under the California Consumer Privacy Act (CCPA).

## Personal information we collect

| Category | Examples | Collected? |
|---|---|---|
| Identifiers | Email, name, IP address | Yes |
| Commercial information | Purchase history | Yes |
| Internet activity | Pages visited, features used | Yes |
| Inferences | Usage patterns | Yes |
| Financial data | Credit card numbers | No — Stripe handles this |

## How we use personal information

We use your information to:
- Provide and improve ${appName}
- Process payments (via Stripe)
- Send transactional emails (via Resend)
- Prevent fraud and abuse

We do **not** sell your personal information.

## Your CCPA rights

As a California resident you have the right to:
- **Know** what personal information we collect and how we use it
- **Delete** your personal information (subject to exceptions)
- **Opt-out** of the sale of your personal information (we do not sell data)
- **Non-discrimination** — we will not discriminate for exercising your rights

To submit a request, email [privacy@yourdomain.com] or use the form at [/privacy-request].
We will respond within 45 days.
`;
}

function termsTemplate(appName: string): string {
  return `# Terms of Service — ${appName}

> **Last updated:** ${new Date().toISOString().split('T')[0]}
> **Generated by Prodify — replace all [PLACEHOLDERS] before publishing.**

By using ${appName} you agree to these terms.

## 1. Acceptance

By accessing or using ${appName} ("Service"), you agree to be bound by these Terms of Service.

## 2. Use of the Service

You may use the Service only for lawful purposes and in accordance with these Terms.

## 3. Accounts

You are responsible for maintaining the security of your account credentials.

## 4. Payment

[Describe your billing terms, cancellation policy, and refund policy here.]

## 5. Intellectual property

The Service and its original content are and will remain the exclusive property of [Your Company Name].

## 6. Termination

We may terminate or suspend your account at any time for breach of these Terms.

## 7. Limitation of liability

To the maximum extent permitted by law, ${appName} shall not be liable for any indirect, incidental, or consequential damages.

## 8. Changes

We reserve the right to modify these terms at any time. We will notify users of material changes by email.

## 9. Contact

Questions? Email [legal@yourdomain.com].
`;
}

// ── Public API ────────────────────────────────────────────────────────────────

export function buildComplianceFiles(answers: ProdifyAnswers): FileEntry[] {
  const { appName, complianceRegion } = answers;

  if (complianceRegion === 'eu-gdpr') {
    return [
      { relativePath: 'prodify-layer/compliance/cookie-banner.tsx', content: cookieBanner(appName) },
      { relativePath: 'prodify-layer/compliance/privacy-policy.md', content: privacyPolicy(appName) },
      { relativePath: 'prodify-layer/compliance/terms.md',           content: termsTemplate(appName) },
    ];
  }

  if (complianceRegion === 'us') {
    return [
      { relativePath: 'prodify-layer/compliance/ccpa-notice.md', content: ccpaNotice(appName) },
      { relativePath: 'prodify-layer/compliance/terms.md',        content: termsTemplate(appName) },
    ];
  }

  // global — minimal terms only
  return [
    { relativePath: 'prodify-layer/compliance/terms.md', content: termsTemplate(appName) },
  ];
}
