// ─── DB Injector ─────────────────────────────────────────────────────────────
// Generates database client setup tailored to BaaS provider, user type, and pricing model.
//   individuals → users + subscriptions + webhook_events
//   teams       → + organizations + memberships
//   enterprise  → + saml_config on organizations
//   credits     → + credit_ledger + credits_remaining on users
//   freemium    → + free_usage tracking table
//   dbProvider  → 'insforge' generates insforge.ts, 'supabase' generates supabase.ts
import type { FileEntry, UserType, PricingModel, OnboardingFlow, DbProvider } from '../types';

// ── InsForge client singleton ─────────────────────────────────────────────────

const insforgeClientFile = `// prodify-layer/db/insforge.ts
// Generated by Prodify — InsForge BaaS client singleton
import { createClient } from '@insforge/sdk';

const globalForInsforge = globalThis as unknown as {
  insforge: ReturnType<typeof createClient>;
};

function makeClient() {
  return createClient({
    baseUrl: process.env.INSFORGE_URL!,
    anonKey: process.env.INSFORGE_ANON_KEY,
    isServerMode: true,
  });
}

export const insforge = globalForInsforge.insforge ?? makeClient();

if (process.env.NODE_ENV !== 'production') {
  globalForInsforge.insforge = insforge;
}
`;

// ── Supabase client singleton ─────────────────────────────────────────────────

const supabaseClientFile = `// prodify-layer/db/supabase.ts
// Generated by Prodify — Supabase client singleton (server-side)
// Uses SUPABASE_SERVICE_ROLE_KEY for server-only API routes.
// For browser/client components use NEXT_PUBLIC_SUPABASE_ANON_KEY instead.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';

const globalForSupabase = globalThis as unknown as {
  supabase: SupabaseClient;
};

// Server-only client — never import in client components or pages
export const supabase =
  globalForSupabase.supabase ??
  createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
  );

if (process.env.NODE_ENV !== 'production') {
  globalForSupabase.supabase = supabase;
}
`;

// ── Base table definitions ────────────────────────────────────────────────────

function baseUsersTable(hasCredits: boolean): string {
  const creditsCol = hasCredits
    ? `  credits_remaining  INT NOT NULL DEFAULT 0,       -- decremented on each AI call / action`
    : '';
  return `CREATE TABLE IF NOT EXISTS users (
  id         TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  name       TEXT,
  email      TEXT UNIQUE NOT NULL,
  image      TEXT,
${creditsCol ? creditsCol + '\n' : ''}  created_at TIMESTAMPTZ DEFAULT now()
);`;
}

const subscriptionsTable = `CREATE TABLE IF NOT EXISTS subscriptions (
  id                     TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  user_id                TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  stripe_customer_id     TEXT UNIQUE,
  stripe_subscription_id TEXT UNIQUE,
  stripe_monthly_price_id TEXT,
  stripe_annual_price_id  TEXT,
  billing_interval        TEXT DEFAULT 'monthly', -- 'monthly' | 'annual'
  status                 TEXT DEFAULT 'inactive', -- 'active' | 'trialing' | 'past_due' | 'cancelled'
  trial_end              TIMESTAMPTZ,
  current_period_end     TIMESTAMPTZ,
  created_at             TIMESTAMPTZ DEFAULT now()
);`;

const webhookEventsTable = `CREATE TABLE IF NOT EXISTS webhook_events (
  id              TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  stripe_event_id TEXT UNIQUE NOT NULL,
  type            TEXT NOT NULL,
  payload         TEXT NOT NULL,
  processed_at    TIMESTAMPTZ DEFAULT now()
);`;

const creditLedgerTable = `-- Credit ledger: every credit transaction is a row for full audit trail
CREATE TABLE IF NOT EXISTS credit_ledger (
  id          TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  user_id     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  amount      INT NOT NULL,  -- positive = purchase/gift, negative = usage
  reason      TEXT NOT NULL, -- e.g. 'credit-purchase-starter', 'ai-call', 'trial-grant', 'refund'
  metadata    JSONB,         -- e.g. { "stripe_payment_intent": "pi_xxx" }
  created_at  TIMESTAMPTZ DEFAULT now()
);

-- Index for fetching a user's balance history efficiently
CREATE INDEX IF NOT EXISTS idx_credit_ledger_user_created ON credit_ledger(user_id, created_at DESC);`;

const freeUsageTable = `-- Freemium usage tracker: tracks resource consumption per user per period
CREATE TABLE IF NOT EXISTS free_usage (
  id          TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  user_id     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  resource    TEXT NOT NULL,  -- e.g. 'projects', 'api_calls', 'analyses'
  count       INT NOT NULL DEFAULT 0,
  period      TEXT NOT NULL,  -- e.g. '2025-04' (YYYY-MM for monthly limits)
  created_at  TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, resource, period)
);`;

const orgsTable = `CREATE TABLE IF NOT EXISTS organizations (
  id         TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  name       TEXT NOT NULL,
  slug       TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);`;

const orgsWithSamlTable = `CREATE TABLE IF NOT EXISTS organizations (
  id          TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  name        TEXT NOT NULL,
  slug        TEXT UNIQUE NOT NULL,
  saml_config JSONB,  -- BoxyHQ SAML/SSO configuration
  created_at  TIMESTAMPTZ DEFAULT now()
);`;

const membershipsTable = `CREATE TABLE IF NOT EXISTS memberships (
  id              TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  user_id         TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  role            TEXT DEFAULT 'member',  -- 'owner' | 'admin' | 'member'
  created_at      TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, organization_id)
);`;

// ── Schema assembly ───────────────────────────────────────────────────────────

function buildSchema(
  userType: UserType,
  pricingModel: PricingModel,
  onboardingFlow: OnboardingFlow,
  dbProvider: DbProvider,
): string {
  const hasCredits = pricingModel === 'credits';
  const hasFreemium = onboardingFlow === 'freemium';
  const providerLabel = dbProvider === 'supabase' ? 'Supabase' : 'InsForge';
  const editorHint = dbProvider === 'supabase'
    ? '-- Run this in your Supabase project SQL Editor (Table Editor → SQL → New query)'
    : '-- Run this in your InsForge project SQL editor or migration tool';

  const blocks: string[] = [
    `-- Generated by Prodify — ${userType} schema for ${providerLabel}`,
    editorHint,
    ``,
    baseUsersTable(hasCredits),
    ``,
    subscriptionsTable,
    ``,
    webhookEventsTable,
  ];

  if (hasCredits) {
    blocks.push(``, creditLedgerTable);
  }

  if (hasFreemium) {
    blocks.push(``, freeUsageTable);
  }

  if (userType === 'teams') {
    blocks.push(``, orgsTable, ``, membershipsTable);
  }

  if (userType === 'enterprise') {
    blocks.push(``, orgsWithSamlTable, ``, membershipsTable);
  }

  return blocks.join('\n');
}

// ── Public API ────────────────────────────────────────────────────────────────

export function buildDbFiles(
  userType: UserType,
  pricingModel: PricingModel,
  onboardingFlow: OnboardingFlow,
  dbProvider: DbProvider = 'insforge',
): FileEntry[] {
  const schema = buildSchema(userType, pricingModel, onboardingFlow, dbProvider);

  const clientFile = dbProvider === 'supabase'
    ? { relativePath: 'prodify-layer/db/supabase.ts', content: supabaseClientFile }
    : { relativePath: 'prodify-layer/db/insforge.ts', content: insforgeClientFile };

  return [
    clientFile,
    { relativePath: 'prodify-layer/db/schema.sql', content: schema },
  ];
}
