// ─── DB Injector ─────────────────────────────────────────────────────────────
// Generates a Prisma schema tailored to the user type.
//   individuals → User + Account + Session + Subscription + WebhookEvent
//   teams       → + Organization + Membership
//   enterprise  → + samlConfig field on Organization
import type { FileEntry, UserType } from '../types';

// ── Schema preamble (shared) ──────────────────────────────────────────────────
const PREAMBLE = `// prodify-layer/db/schema.prisma
// Generated by Prodify — copy to prisma/schema.prisma (or merge with existing)

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

`;

// ── Model blocks ──────────────────────────────────────────────────────────────

const USER_MODEL = `model User {
  id            String         @id @default(cuid())
  name          String?
  email         String         @unique
  emailVerified DateTime?
  image         String?
  createdAt     DateTime       @default(now())
  accounts      Account[]
  sessions      Session[]
  subscriptions Subscription[]
}

`;

const ACCOUNT_SESSION_MODELS = `model Account {
  id                String  @id @default(cuid())
  userId            String
  type              String
  provider          String
  providerAccountId String
  refresh_token     String?
  access_token      String?
  expires_at        Int?
  user              User    @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
}

model Session {
  id           String   @id @default(cuid())
  sessionToken String   @unique
  userId       String
  expires      DateTime
  user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)
}

`;

const SUBSCRIPTION_MODEL = `model Subscription {
  id                   String    @id @default(cuid())
  userId               String
  stripeCustomerId     String    @unique
  stripeSubscriptionId String?   @unique
  stripePriceId        String?
  status               String    @default("inactive")
  currentPeriodEnd     DateTime?
  createdAt            DateTime  @default(now())
  user                 User      @relation(fields: [userId], references: [id], onDelete: Cascade)
}

`;

const WEBHOOK_EVENT_MODEL = `model WebhookEvent {
  id             String   @id @default(cuid())
  stripeEventId  String   @unique
  type           String
  payload        String   @db.Text
  processedAt    DateTime @default(now())
}

`;

const ORGANIZATION_MODEL = `model Organization {
  id          String       @id @default(cuid())
  name        String
  slug        String       @unique
  createdAt   DateTime     @default(now())
  memberships Membership[]
}

`;

const ENTERPRISE_ORGANIZATION_MODEL = `model Organization {
  id          String       @id @default(cuid())
  name        String
  slug        String       @unique
  samlConfig  String?      // JSON: BoxyHQ/Jackson SAML IdP config
  createdAt   DateTime     @default(now())
  memberships Membership[]
}

`;

const MEMBERSHIP_MODEL = `model Membership {
  id             String       @id @default(cuid())
  userId         String
  organizationId String
  role           String       @default("member") // "owner" | "admin" | "member"
  createdAt      DateTime     @default(now())
  organization   Organization @relation(fields: [organizationId], references: [id], onDelete: Cascade)

  @@unique([userId, organizationId])
}

`;

// ── Public API ────────────────────────────────────────────────────────────────

export function buildDbFiles(userType: UserType): FileEntry[] {
  let schema = PREAMBLE + USER_MODEL + ACCOUNT_SESSION_MODELS + SUBSCRIPTION_MODEL + WEBHOOK_EVENT_MODEL;

  if (userType === 'teams') {
    schema += ORGANIZATION_MODEL + MEMBERSHIP_MODEL;
  } else if (userType === 'enterprise') {
    schema += ENTERPRISE_ORGANIZATION_MODEL + MEMBERSHIP_MODEL;
  }

  return [{ relativePath: 'prodify-layer/db/schema.prisma', content: schema }];
}
