// ─── DB Injector ─────────────────────────────────────────────────────────────
// Generates InsForge database client setup tailored to the user type.
//   individuals → users + subscriptions + webhook_events tables
//   teams       → + organizations + memberships tables
//   enterprise  → + saml_config on organizations
import type { FileEntry, UserType } from '../types';

// ── InsForge client singleton ─────────────────────────────────────────────────

const insforgeClient = `// prodify-layer/db/insforge.ts
// Generated by Prodify — InsForge BaaS client singleton
import { createClient } from '@insforge/sdk';

const globalForInsforge = globalThis as unknown as {
  insforge: ReturnType<typeof createClient>;
};

function makeClient() {
  return createClient({
    baseUrl: process.env.INSFORGE_URL!,
    anonKey: process.env.INSFORGE_ANON_KEY,
    isServerMode: true,
  });
}

export const insforge = globalForInsforge.insforge ?? makeClient();

if (process.env.NODE_ENV !== 'production') {
  globalForInsforge.insforge = insforge;
}
`;

// ── Table definition helpers ──────────────────────────────────────────────────

const individualsSchema = `// prodify-layer/db/schema.sql
-- Generated by Prodify — individuals schema for InsForge
-- Run this in your InsForge project SQL editor or migration tool

CREATE TABLE IF NOT EXISTS users (
  id         TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  name       TEXT,
  email      TEXT UNIQUE NOT NULL,
  image      TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS subscriptions (
  id                     TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  user_id                TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  stripe_customer_id     TEXT UNIQUE,
  stripe_subscription_id TEXT UNIQUE,
  stripe_price_id        TEXT,
  status                 TEXT DEFAULT 'inactive',
  current_period_end     TIMESTAMPTZ,
  created_at             TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS webhook_events (
  id              TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  stripe_event_id TEXT UNIQUE NOT NULL,
  type            TEXT NOT NULL,
  payload         TEXT NOT NULL,
  processed_at    TIMESTAMPTZ DEFAULT now()
);
`;

const teamsSchema = individualsSchema + `
CREATE TABLE IF NOT EXISTS organizations (
  id         TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  name       TEXT NOT NULL,
  slug       TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS memberships (
  id              TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  user_id         TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  role            TEXT DEFAULT 'member',
  created_at      TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, organization_id)
);
`;

const enterpriseSchema = individualsSchema + `
CREATE TABLE IF NOT EXISTS organizations (
  id          TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  name        TEXT NOT NULL,
  slug        TEXT UNIQUE NOT NULL,
  saml_config JSONB,
  created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS memberships (
  id              TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  user_id         TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  role            TEXT DEFAULT 'member',
  created_at      TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, organization_id)
);
`;

// ── Public API ────────────────────────────────────────────────────────────────

export function buildDbFiles(userType: UserType): FileEntry[] {
  const schema =
    userType === 'enterprise'
      ? enterpriseSchema
      : userType === 'teams'
      ? teamsSchema
      : individualsSchema;

  return [
    { relativePath: 'prodify-layer/db/insforge.ts', content: insforgeClient },
    { relativePath: 'prodify-layer/db/schema.sql', content: schema },
  ];
}
