// ─── Email Injector ───────────────────────────────────────────────────────────
// Generates a Resend client singleton and three React Email templates:
//   welcome.tsx      — sent on first sign-in
//   trial-ending.tsx — sent 3 days before trial expires
//   receipt.tsx      — sent after successful Stripe payment
import type { FileEntry, ProdifyAnswers } from '../types';

function resendClient(appName: string): string {
  return `// prodify-layer/email/client.ts
// Generated by Prodify — Resend email client singleton
import { Resend } from 'resend';

const globalForResend = globalThis as unknown as { resend: Resend };

export const resend = globalForResend.resend ?? new Resend(process.env.RESEND_API_KEY!);

if (process.env.NODE_ENV !== 'production') {
  globalForResend.resend = resend;
}

/** Default sender address — set FROM_EMAIL in your .env */
export const FROM = process.env.FROM_EMAIL ?? 'hello@${appName.toLowerCase().replace(/\s+/g, '')}.com';

/** Utility to send a transactional email */
export async function sendEmail(params: {
  to: string;
  subject: string;
  react: React.ReactElement;
}): Promise<void> {
  const { error } = await resend.emails.send({
    from: FROM,
    to: params.to,
    subject: params.subject,
    react: params.react,
  });
  if (error) {
    console.error('[resend] Failed to send email:', error);
    throw new Error(\`Email send failed: \${error.message}\`);
  }
}
`;
}

function welcomeTemplate(appName: string): string {
  return `// prodify-layer/email/templates/welcome.tsx
// Generated by Prodify — Welcome email template (React Email)
// Install: npm install @react-email/components
import {
  Html, Head, Body, Container, Section,
  Heading, Text, Button, Hr, Link,
} from '@react-email/components';
import * as React from 'react';

interface WelcomeEmailProps {
  userName?: string;
  loginUrl?: string;
}

export function WelcomeEmail({
  userName = 'there',
  loginUrl = process.env.NEXT_PUBLIC_APP_URL ?? 'http://localhost:3000',
}: WelcomeEmailProps) {
  return (
    <Html>
      <Head />
      <Body style={{ backgroundColor: '#f6f9fc', fontFamily: 'sans-serif' }}>
        <Container style={{ maxWidth: '600px', margin: '0 auto', padding: '40px 20px' }}>
          <Heading style={{ color: '#1a1b2e', fontSize: '24px' }}>
            Welcome to ${appName} 👋
          </Heading>
          <Text style={{ color: '#555', fontSize: '16px', lineHeight: '24px' }}>
            Hey {userName}, thanks for joining ${appName}! Your account is ready.
          </Text>
          <Section style={{ textAlign: 'center', margin: '32px 0' }}>
            <Button
              href={loginUrl}
              style={{
                background: '#575efe',
                color: '#fff',
                padding: '12px 24px',
                borderRadius: '8px',
                textDecoration: 'none',
                fontWeight: '600',
              }}
            >
              Get started →
            </Button>
          </Section>
          <Hr style={{ borderColor: '#e6ebf1' }} />
          <Text style={{ color: '#999', fontSize: '12px' }}>
            You&apos;re receiving this because you created an account at ${appName}.
            Questions? Reply to this email.
          </Text>
        </Container>
      </Body>
    </Html>
  );
}

export default WelcomeEmail;
`;
}

function trialEndingTemplate(appName: string): string {
  return `// prodify-layer/email/templates/trial-ending.tsx
// Generated by Prodify — Trial ending email template (React Email)
import {
  Html, Head, Body, Container,
  Heading, Text, Button, Hr,
} from '@react-email/components';
import * as React from 'react';

interface TrialEndingEmailProps {
  userName?: string;
  daysLeft?: number;
  upgradeUrl?: string;
}

export function TrialEndingEmail({
  userName = 'there',
  daysLeft = 3,
  upgradeUrl = \`\${process.env.NEXT_PUBLIC_APP_URL ?? 'http://localhost:3000'}/pricing\`,
}: TrialEndingEmailProps) {
  return (
    <Html>
      <Head />
      <Body style={{ backgroundColor: '#f6f9fc', fontFamily: 'sans-serif' }}>
        <Container style={{ maxWidth: '600px', margin: '0 auto', padding: '40px 20px' }}>
          <Heading style={{ color: '#1a1b2e', fontSize: '24px' }}>
            Your ${appName} trial ends in {daysLeft} day{daysLeft !== 1 ? 's' : ''} ⏳
          </Heading>
          <Text style={{ color: '#555', fontSize: '16px', lineHeight: '24px' }}>
            Hey {userName}, your free trial is almost up. Upgrade now to keep access to
            everything you&apos;ve built.
          </Text>
          <Section style={{ textAlign: 'center', margin: '32px 0' }}>
            <Button
              href={upgradeUrl}
              style={{
                background: '#575efe',
                color: '#fff',
                padding: '12px 24px',
                borderRadius: '8px',
                textDecoration: 'none',
                fontWeight: '600',
              }}
            >
              Upgrade now →
            </Button>
          </Section>
          <Hr style={{ borderColor: '#e6ebf1' }} />
          <Text style={{ color: '#999', fontSize: '12px' }}>
            ${appName} · You&apos;re receiving this because your free trial is ending.
          </Text>
        </Container>
      </Body>
    </Html>
  );
}

export default TrialEndingEmail;
`;
}

function receiptTemplate(appName: string): string {
  return `// prodify-layer/email/templates/receipt.tsx
// Generated by Prodify — Payment receipt email template (React Email)
// Trigger this from the checkout.session.completed webhook handler.
import {
  Html, Head, Body, Container, Section,
  Heading, Text, Button, Hr, Row, Column,
} from '@react-email/components';
import * as React from 'react';

interface ReceiptEmailProps {
  userName?: string;
  amount?: string;        // formatted, e.g. "$19.00"
  planName?: string;      // e.g. "Pro — Monthly"
  receiptUrl?: string;    // Stripe-hosted receipt URL from checkout.session
  dashboardUrl?: string;
}

export function ReceiptEmail({
  userName = 'there',
  amount = '--',
  planName = '${appName} Pro',
  receiptUrl,
  dashboardUrl = process.env.NEXT_PUBLIC_APP_URL ?? 'http://localhost:3000',
}: ReceiptEmailProps) {
  return (
    <Html>
      <Head />
      <Body style={{ backgroundColor: '#f6f9fc', fontFamily: 'sans-serif' }}>
        <Container style={{ maxWidth: '600px', margin: '0 auto', padding: '40px 20px' }}>
          <Heading style={{ color: '#1a1b2e', fontSize: '24px' }}>
            Payment confirmed ✓
          </Heading>
          <Text style={{ color: '#555', fontSize: '16px' }}>
            Thanks {userName}! Your payment was successful.
          </Text>
          <Section style={{ background: '#fff', borderRadius: '8px', padding: '24px', margin: '24px 0', border: '1px solid #e6ebf1' }}>
            <Row>
              <Column><Text style={{ color: '#999', margin: 0 }}>Plan</Text></Column>
              <Column style={{ textAlign: 'right' }}><Text style={{ fontWeight: '600', margin: 0 }}>{planName}</Text></Column>
            </Row>
            <Row>
              <Column><Text style={{ color: '#999', margin: 0 }}>Amount</Text></Column>
              <Column style={{ textAlign: 'right' }}><Text style={{ fontWeight: '600', margin: 0 }}>{amount}</Text></Column>
            </Row>
          </Section>
          <Section style={{ textAlign: 'center', margin: '24px 0' }}>
            <Button
              href={dashboardUrl}
              style={{ background: '#575efe', color: '#fff', padding: '12px 24px', borderRadius: '8px', textDecoration: 'none', fontWeight: '600' }}
            >
              Go to dashboard →
            </Button>
            {receiptUrl && (
              <Text style={{ marginTop: '12px' }}>
                <a href={receiptUrl} style={{ color: '#575efe' }}>View full receipt</a>
              </Text>
            )}
          </Section>
          <Hr style={{ borderColor: '#e6ebf1' }} />
          <Text style={{ color: '#999', fontSize: '12px' }}>
            ${appName} · This is a payment confirmation for your records.
          </Text>
        </Container>
      </Body>
    </Html>
  );
}

export default ReceiptEmail;
`;
}

// ── Public API ────────────────────────────────────────────────────────────────

export function buildEmailFiles(answers: ProdifyAnswers): FileEntry[] {
  const { appName } = answers;

  return [
    { relativePath: 'prodify-layer/email/client.ts',                    content: resendClient(appName) },
    { relativePath: 'prodify-layer/email/templates/welcome.tsx',        content: welcomeTemplate(appName) },
    { relativePath: 'prodify-layer/email/templates/trial-ending.tsx',   content: trialEndingTemplate(appName) },
    { relativePath: 'prodify-layer/email/templates/receipt.tsx',        content: receiptTemplate(appName) },
  ];
}
