// ─── ENV Injector ─────────────────────────────────────────────────────────────
// Generates a .env.example with all required keys, labeled by service.
import type { FileEntry, ProdifyAnswers } from '../types';

export function buildEnvFile(answers: ProdifyAnswers): FileEntry[] {
  const samlBlock =
    answers.userType === 'enterprise'
      ? `
# ── SAML / Enterprise SSO ─────────────────────────────────────────────────────
SAML_AUTHORIZATION_URL=        # Your IdP authorization endpoint
SAML_TOKEN_URL=                # Your IdP token endpoint
SAML_USERINFO_URL=             # Your IdP userinfo endpoint
SAML_CLIENT_ID=                # Client ID from your IdP
SAML_CLIENT_SECRET=            # Client secret from your IdP
`
      : '';

  const content = `# ─── Generated by Prodify ────────────────────────────────────────────────────
# Copy this file to .env.local and fill in all values before running.
# Never commit .env.local to git.

# ── Database ──────────────────────────────────────────────────────────────────
DATABASE_URL=postgresql://user:password@localhost:5432/mydb

# ── NextAuth.js ───────────────────────────────────────────────────────────────
NEXTAUTH_URL=http://localhost:3000
NEXTAUTH_SECRET=               # Run: openssl rand -base64 32

# ── OAuth Providers ───────────────────────────────────────────────────────────
GOOGLE_CLIENT_ID=              # console.cloud.google.com → Credentials
GOOGLE_CLIENT_SECRET=
GITHUB_CLIENT_ID=              # github.com → Settings → Developer settings
GITHUB_CLIENT_SECRET=
${samlBlock}
# ── Stripe ────────────────────────────────────────────────────────────────────
STRIPE_SECRET_KEY=sk_test_     # dashboard.stripe.com → Developers → API keys
STRIPE_PUBLISHABLE_KEY=pk_test_
STRIPE_WEBHOOK_SECRET=whsec_   # stripe listen --forward-to localhost:3000/api/webhooks/stripe
STRIPE_PRICE_ID=price_         # The price ID for your subscription plan

# ── App ────────────────────────────────────────────────────────────────────────
NEXT_PUBLIC_APP_URL=http://localhost:3000
`;

  return [{ relativePath: '.env.example', content }];
}
