// ─── Payments Injector ────────────────────────────────────────────────────────
// Generates Stripe helpers and API route files based on the pricing model.
//   per-seat → per-unit subscription line items
//   flat     → single flat-rate subscription
//   usage    → metered (usage-based) billing with reportUsage helper
import type { FileEntry, PricingModel } from '../types';

// ── Stripe helper templates ───────────────────────────────────────────────────

function perSeatStripe(): string {
  return `// prodify-layer/payments/stripe.ts
// Generated by Prodify — per-seat Stripe billing helpers
import Stripe from 'stripe';

export const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: '2024-04-10',
});

/** Create a checkout session for per-seat billing */
export async function createPerSeatCheckout(params: {
  customerId: string;
  priceId: string;      // e.g. price_xxx — your per_unit price in Stripe
  quantity: number;     // number of seats
  successUrl: string;
  cancelUrl: string;
}): Promise<Stripe.Checkout.Session> {
  return stripe.checkout.sessions.create({
    customer: params.customerId,
    mode: 'subscription',
    line_items: [
      {
        price: params.priceId,
        quantity: params.quantity,
        adjustable_quantity: { enabled: true, minimum: 1 },
      },
    ],
    success_url: params.successUrl,
    cancel_url: params.cancelUrl,
  });
}
`;
}

function flatStripe(): string {
  return `// prodify-layer/payments/stripe.ts
// Generated by Prodify — flat subscription Stripe billing helpers
import Stripe from 'stripe';

export const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: '2024-04-10',
});

/** Create a checkout session for a flat subscription */
export async function createFlatSubscription(params: {
  customerId: string;
  priceId: string;   // e.g. price_xxx — your flat monthly/annual price in Stripe
  successUrl: string;
  cancelUrl: string;
}): Promise<Stripe.Checkout.Session> {
  return stripe.checkout.sessions.create({
    customer: params.customerId,
    mode: 'subscription',
    line_items: [{ price: params.priceId, quantity: 1 }],
    success_url: params.successUrl,
    cancel_url: params.cancelUrl,
  });
}
`;
}

function usageStripe(): string {
  return `// prodify-layer/payments/stripe.ts
// Generated by Prodify — usage-based (metered) Stripe billing helpers
import Stripe from 'stripe';

export const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: '2024-04-10',
});

/** Create a checkout session for metered (usage-based) billing */
export async function createUsageSubscription(params: {
  customerId: string;
  priceId: string;   // Stripe price with aggregate_usage: 'sum'
  successUrl: string;
  cancelUrl: string;
}): Promise<Stripe.Checkout.Session> {
  return stripe.checkout.sessions.create({
    customer: params.customerId,
    mode: 'subscription',
    line_items: [{ price: params.priceId }],  // no quantity for metered
    success_url: params.successUrl,
    cancel_url: params.cancelUrl,
  });
}

/** Report usage units for a subscription item */
export async function reportUsage(params: {
  subscriptionItemId: string;
  quantity: number;
  timestamp?: number;
}): Promise<Stripe.UsageRecord> {
  return stripe.subscriptionItems.createUsageRecord(
    params.subscriptionItemId,
    {
      quantity: params.quantity,
      timestamp: params.timestamp ?? Math.floor(Date.now() / 1000),
      action: 'increment',
    },
  );
}
`;
}

// ── Shared route templates ────────────────────────────────────────────────────

const checkoutRoute = `// prodify-layer/routes/api/checkout/route.ts
// Drop into app/api/checkout/route.ts
import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/prodify-layer/auth/[...nextauth]';
import { stripe } from '@/prodify-layer/payments/stripe';

export async function POST(req: Request) {
  const session = await getServerSession(authOptions);
  if (!session?.user?.id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const { priceId, quantity } = await req.json() as { priceId: string; quantity?: number };
  const origin = req.headers.get('origin') ?? 'http://localhost:3000';

  // TODO: look up Stripe customerId from DB using session.user.id
  const customerId = 'cus_placeholder';

  const checkoutSession = await stripe.checkout.sessions.create({
    customer: customerId,
    mode: 'subscription',
    line_items: [{ price: priceId, quantity: quantity ?? 1 }],
    success_url: \`\${origin}/dashboard?success=1\`,
    cancel_url: \`\${origin}/pricing?canceled=1\`,
  });

  return NextResponse.json({ url: checkoutSession.url });
}
`;

const webhookRoute = `// prodify-layer/routes/api/webhooks/stripe/route.ts
// Drop into app/api/webhooks/stripe/route.ts
import { NextResponse } from 'next/server';
import { stripe } from '@/prodify-layer/payments/stripe';
import { prisma } from '@/lib/prisma';
import Stripe from 'stripe';

export async function POST(req: Request) {
  const body = await req.text();
  const sig = req.headers.get('stripe-signature')!;

  let event: Stripe.Event;
  try {
    event = stripe.webhooks.constructEvent(
      body,
      sig,
      process.env.STRIPE_WEBHOOK_SECRET!,
    );
  } catch (err) {
    return NextResponse.json({ error: 'Webhook signature failed' }, { status: 400 });
  }

  // Persist raw event for idempotency / replay
  await prisma.webhookEvent.upsert({
    where: { stripeEventId: event.id },
    create: { stripeEventId: event.id, type: event.type, payload: JSON.stringify(event) },
    update: {},
  });

  switch (event.type) {
    case 'checkout.session.completed': {
      const session = event.data.object as Stripe.Checkout.Session;
      // TODO: provision access, update subscription status in DB
      console.log('Checkout complete:', session.id);
      break;
    }
    case 'customer.subscription.deleted': {
      const sub = event.data.object as Stripe.Subscription;
      // TODO: revoke access in DB
      console.log('Subscription cancelled:', sub.id);
      break;
    }
  }

  return NextResponse.json({ received: true });
}
`;

const portalRoute = `// prodify-layer/routes/api/portal/route.ts
// Drop into app/api/portal/route.ts — Stripe Customer Portal redirect
import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/prodify-layer/auth/[...nextauth]';
import { stripe } from '@/prodify-layer/payments/stripe';

export async function POST(req: Request) {
  const session = await getServerSession(authOptions);
  if (!session?.user?.id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const origin = req.headers.get('origin') ?? 'http://localhost:3000';

  // TODO: look up Stripe customerId from DB using session.user.id
  const customerId = 'cus_placeholder';

  const portalSession = await stripe.billingPortal.sessions.create({
    customer: customerId,
    return_url: \`\${origin}/dashboard\`,
  });

  return NextResponse.json({ url: portalSession.url });
}
`;

// ── Public API ────────────────────────────────────────────────────────────────

export function buildPaymentsFiles(pricingModel: PricingModel): FileEntry[] {
  const stripeContent =
    pricingModel === 'usage'
      ? usageStripe()
      : pricingModel === 'flat'
      ? flatStripe()
      : perSeatStripe();

  return [
    { relativePath: 'prodify-layer/payments/stripe.ts', content: stripeContent },
    { relativePath: 'prodify-layer/routes/api/checkout/route.ts', content: checkoutRoute },
    { relativePath: 'prodify-layer/routes/api/webhooks/stripe/route.ts', content: webhookRoute },
    { relativePath: 'prodify-layer/routes/api/portal/route.ts', content: portalRoute },
  ];
}
