// ─── Payments Injector ────────────────────────────────────────────────────────
// Generates Stripe helpers and API route files based on the pricing model,
// billing interval, and onboarding flow.
//
//   flat       → single flat-rate subscription (monthly or annual price IDs)
//   per-seat   → per-unit subscription line items (monthly or annual)
//   usage      → metered checkout (aggregate_usage: sum price)
//   hybrid     → flat base subscription + usage overage item on the same subscription
//   one-time   → payment_intent mode checkout (not subscription)
//   credits    → one-time payment for a credit pack + DB ledger helper
//
//   onboardingFlow = trial-* → adds trial_period_days to checkout session
//   billingInterval = annual → injects STRIPE_ANNUAL_PRICE_ID env + billing toggle helper
import type { FileEntry, PricingModel, BillingInterval, OnboardingFlow } from '../types';

// ── Trial helper ──────────────────────────────────────────────────────────────

function trialBlock(onboardingFlow: OnboardingFlow): string {
  if (onboardingFlow === 'trial-card' || onboardingFlow === 'trial-no-card') {
    return `    trial_period_days: parseInt(process.env.STRIPE_FREE_TRIAL_DAYS ?? '14'),`;
  }
  return '';
}

// ── Stripe helper templates ───────────────────────────────────────────────────

function flatStripe(billingInterval: BillingInterval, onboardingFlow: OnboardingFlow): string {
  const priceEnvKey = billingInterval === 'annual'
    ? '// Pass priceId as STRIPE_MONTHLY_PRICE_ID or STRIPE_ANNUAL_PRICE_ID depending on user choice'
    : '// Pass priceId as STRIPE_MONTHLY_PRICE_ID';
  const trial = trialBlock(onboardingFlow);
  return `// prodify-layer/payments/stripe.ts
// Generated by Prodify — flat subscription Stripe billing helpers
import Stripe from 'stripe';

export const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: '2024-04-10',
});

${priceEnvKey}
export async function createFlatSubscription(params: {
  customerId: string;
  priceId: string;
  successUrl: string;
  cancelUrl: string;
}): Promise<Stripe.Checkout.Session> {
  return stripe.checkout.sessions.create({
    customer: params.customerId,
    mode: 'subscription',
    line_items: [{ price: params.priceId, quantity: 1 }],
    ${trial}
    success_url: params.successUrl,
    cancel_url: params.cancelUrl,
  });
}
`;
}

function perSeatStripe(billingInterval: BillingInterval, onboardingFlow: OnboardingFlow): string {
  const trial = trialBlock(onboardingFlow);
  return `// prodify-layer/payments/stripe.ts
// Generated by Prodify — per-seat Stripe billing helpers
import Stripe from 'stripe';

export const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: '2024-04-10',
});

/** Create a checkout session for per-seat billing.
 *  priceId = STRIPE_MONTHLY_PRICE_ID or STRIPE_ANNUAL_PRICE_ID (per_unit price)
 */
export async function createPerSeatCheckout(params: {
  customerId: string;
  priceId: string;
  quantity: number;
  successUrl: string;
  cancelUrl: string;
}): Promise<Stripe.Checkout.Session> {
  return stripe.checkout.sessions.create({
    customer: params.customerId,
    mode: 'subscription',
    line_items: [
      {
        price: params.priceId,
        quantity: params.quantity,
        adjustable_quantity: { enabled: true, minimum: 1 },
      },
    ],
    ${trial}
    success_url: params.successUrl,
    cancel_url: params.cancelUrl,
  });
}
`;
}

function usageStripe(onboardingFlow: OnboardingFlow): string {
  const trial = trialBlock(onboardingFlow);
  return `// prodify-layer/payments/stripe.ts
// Generated by Prodify — usage-based (metered) Stripe billing helpers
import Stripe from 'stripe';

export const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: '2024-04-10',
});

/** Create a checkout session for metered (usage-based) billing.
 *  priceId = a Stripe price with aggregate_usage: 'sum' and billing_scheme: 'per_unit'
 */
export async function createUsageSubscription(params: {
  customerId: string;
  priceId: string;
  successUrl: string;
  cancelUrl: string;
}): Promise<Stripe.Checkout.Session> {
  return stripe.checkout.sessions.create({
    customer: params.customerId,
    mode: 'subscription',
    line_items: [{ price: params.priceId }],  // no quantity for metered
    ${trial}
    success_url: params.successUrl,
    cancel_url: params.cancelUrl,
  });
}

/** Report usage units for a subscription item (call after each billable event) */
export async function reportUsage(params: {
  subscriptionItemId: string;
  quantity: number;
  timestamp?: number;
}): Promise<Stripe.UsageRecord> {
  return stripe.subscriptionItems.createUsageRecord(
    params.subscriptionItemId,
    {
      quantity: params.quantity,
      timestamp: params.timestamp ?? Math.floor(Date.now() / 1000),
      action: 'increment',
    },
  );
}
`;
}

function hybridStripe(billingInterval: BillingInterval, onboardingFlow: OnboardingFlow): string {
  const trial = trialBlock(onboardingFlow);
  return `// prodify-layer/payments/stripe.ts
// Generated by Prodify — hybrid (flat base + usage overages) Stripe billing helpers
// Pattern: think Vercel — $20/month base, then $0.02 per GB over the limit.
// Requires TWO Stripe prices:
//   STRIPE_MONTHLY_PRICE_ID — a flat recurring price (your base subscription)
//   STRIPE_OVERAGE_PRICE_ID — a metered price (aggregate_usage: sum, billed at period end)
import Stripe from 'stripe';

export const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: '2024-04-10',
});

/** Create a checkout session with a flat base + metered overage item */
export async function createHybridSubscription(params: {
  customerId: string;
  successUrl: string;
  cancelUrl: string;
}): Promise<Stripe.Checkout.Session> {
  return stripe.checkout.sessions.create({
    customer: params.customerId,
    mode: 'subscription',
    line_items: [
      { price: process.env.STRIPE_MONTHLY_PRICE_ID!, quantity: 1 },
      { price: process.env.STRIPE_OVERAGE_PRICE_ID! },  // metered, no quantity
    ],
    ${trial}
    success_url: params.successUrl,
    cancel_url: params.cancelUrl,
  });
}

/** Report overage usage (call after each billable event above the flat limit) */
export async function reportOverage(params: {
  subscriptionItemId: string;  // The metered subscription item ID
  quantity: number;
  timestamp?: number;
}): Promise<Stripe.UsageRecord> {
  return stripe.subscriptionItems.createUsageRecord(
    params.subscriptionItemId,
    {
      quantity: params.quantity,
      timestamp: params.timestamp ?? Math.floor(Date.now() / 1000),
      action: 'increment',
    },
  );
}
`;
}

function oneTimeStripe(): string {
  return `// prodify-layer/payments/stripe.ts
// Generated by Prodify — one-time payment Stripe helpers
// Pattern: lifetime deals, templates, courses, one-off tools.
// Uses payment_intent mode (not subscription) — no recurring charges.
import Stripe from 'stripe';

export const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: '2024-04-10',
});

/** Create a one-time payment checkout session.
 *  priceId = STRIPE_ONE_TIME_PRICE_ID (a price with type: 'one_time')
 */
export async function createOneTimeCheckout(params: {
  customerId: string;
  priceId: string;
  successUrl: string;
  cancelUrl: string;
}): Promise<Stripe.Checkout.Session> {
  return stripe.checkout.sessions.create({
    customer: params.customerId,
    mode: 'payment',  // NOT 'subscription' — this is a one-time charge
    line_items: [{ price: params.priceId, quantity: 1 }],
    success_url: params.successUrl,
    cancel_url: params.cancelUrl,
    payment_intent_data: {
      metadata: { type: 'one-time-purchase' },
    },
  });
}
`;
}

function creditsStripe(): string {
  return `// prodify-layer/payments/stripe.ts
// Generated by Prodify — credits / token pool Stripe helpers
//
// Architecture: Stripe is the PAYMENT layer only. Your InsForge/Supabase DB
// is the LEDGER. Flow:
//   1. User buys a credit pack via Stripe Checkout (one-time payment).
//   2. Webhook fires checkout.session.completed → you add credits to their DB row.
//   3. Each AI call or action: decrement credits_remaining in DB.
//   4. Gate the API route when credits_remaining <= 0.
//
// Benefits over Stripe metered: live balance in UI, partial refunds, gifting credits,
// trial credits, no Stripe API call needed to check balance.
import Stripe from 'stripe';

export const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: '2024-04-10',
});

/** Available credit packs — map to price IDs you create in Stripe dashboard */
export const CREDIT_PACKS = {
  starter:  { priceId: process.env.STRIPE_CREDITS_STARTER_PRICE_ID!,  credits: 100,  label: '100 credits' },
  growth:   { priceId: process.env.STRIPE_CREDITS_GROWTH_PRICE_ID!,   credits: 500,  label: '500 credits' },
  scale:    { priceId: process.env.STRIPE_CREDITS_SCALE_PRICE_ID!,    credits: 2000, label: '2,000 credits' },
} as const;

export type CreditPack = keyof typeof CREDIT_PACKS;

/** Create a Stripe Checkout session for purchasing a credit pack */
export async function createCreditPackCheckout(params: {
  customerId: string;
  pack: CreditPack;
  successUrl: string;
  cancelUrl: string;
}): Promise<Stripe.Checkout.Session> {
  const { priceId, credits } = CREDIT_PACKS[params.pack];
  return stripe.checkout.sessions.create({
    customer: params.customerId,
    mode: 'payment',
    line_items: [{ price: priceId, quantity: 1 }],
    success_url: params.successUrl,
    cancel_url: params.cancelUrl,
    payment_intent_data: {
      metadata: {
        type: 'credit-purchase',
        pack: params.pack,
        credits: String(credits),
      },
    },
  });
}
`;
}

// ── Shared route templates ────────────────────────────────────────────────────

function buildCheckoutRoute(pricingModel: PricingModel, onboardingFlow: OnboardingFlow): string {
  if (pricingModel === 'credits') {
    return `// prodify-layer/routes/api/checkout/route.ts
// Drop into app/api/checkout/route.ts
import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/prodify-layer/auth/[...nextauth]';
import { stripe, CREDIT_PACKS } from '@/prodify-layer/payments/stripe';
import type { CreditPack } from '@/prodify-layer/payments/stripe';

export async function POST(req: Request) {
  const session = await getServerSession(authOptions);
  if (!session?.user?.id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const { pack } = await req.json() as { pack: CreditPack };
  if (!CREDIT_PACKS[pack]) {
    return NextResponse.json({ error: 'Invalid credit pack' }, { status: 400 });
  }

  const origin = process.env.NEXT_PUBLIC_APP_URL ?? 'http://localhost:3000';

  // TODO: look up Stripe customerId from DB using session.user.id
  const customerId = 'cus_placeholder';

  const checkoutSession = await stripe.checkout.sessions.create({
    customer: customerId,
    mode: 'payment',
    line_items: [{ price: CREDIT_PACKS[pack].priceId, quantity: 1 }],
    success_url: \`\${origin}/dashboard?credits_added=1\`,
    cancel_url: \`\${origin}/pricing?canceled=1\`,
    payment_intent_data: {
      metadata: { type: 'credit-purchase', pack, credits: String(CREDIT_PACKS[pack].credits) },
    },
  });

  return NextResponse.json({ url: checkoutSession.url });
}
`;
  }

  if (pricingModel === 'one-time') {
    return `// prodify-layer/routes/api/checkout/route.ts
// Drop into app/api/checkout/route.ts
import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/prodify-layer/auth/[...nextauth]';
import { stripe } from '@/prodify-layer/payments/stripe';

export async function POST(req: Request) {
  const session = await getServerSession(authOptions);
  if (!session?.user?.id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const origin = process.env.NEXT_PUBLIC_APP_URL ?? 'http://localhost:3000';

  // TODO: look up Stripe customerId from DB using session.user.id
  const customerId = 'cus_placeholder';

  const checkoutSession = await stripe.checkout.sessions.create({
    customer: customerId,
    mode: 'payment',
    line_items: [{ price: process.env.STRIPE_ONE_TIME_PRICE_ID!, quantity: 1 }],
    success_url: \`\${origin}/dashboard?success=1\`,
    cancel_url: \`\${origin}/pricing?canceled=1\`,
  });

  return NextResponse.json({ url: checkoutSession.url });
}
`;
  }

  // subscription models (flat, per-seat, usage, hybrid)
  const trialLine = (onboardingFlow === 'trial-card' || onboardingFlow === 'trial-no-card')
    ? `    trial_period_days: parseInt(process.env.STRIPE_FREE_TRIAL_DAYS ?? '14'),`
    : '';

  return `// prodify-layer/routes/api/checkout/route.ts
// Drop into app/api/checkout/route.ts
import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/prodify-layer/auth/[...nextauth]';
import { stripe } from '@/prodify-layer/payments/stripe';

export async function POST(req: Request) {
  const session = await getServerSession(authOptions);
  if (!session?.user?.id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const { priceId, quantity } = await req.json() as { priceId: string; quantity?: number };
  const origin = process.env.NEXT_PUBLIC_APP_URL ?? 'http://localhost:3000';

  // TODO: look up Stripe customerId from DB using session.user.id
  const customerId = 'cus_placeholder';

  const checkoutSession = await stripe.checkout.sessions.create({
    customer: customerId,
    mode: 'subscription',
    line_items: [{ price: priceId, quantity: quantity ?? 1 }],
    ${trialLine}
    success_url: \`\${origin}/dashboard?success=1\`,
    cancel_url: \`\${origin}/pricing?canceled=1\`,
  });

  return NextResponse.json({ url: checkoutSession.url });
}
`;
}

const webhookRoute = `// prodify-layer/routes/api/webhooks/stripe/route.ts
// Drop into app/api/webhooks/stripe/route.ts
//
// ⚠️  TRUST NOTE: Prodify never sees your Stripe secret key or your customers'
// payment data. This webhook handler runs inside YOUR deployed app and hits
// YOUR Stripe account. Prodify injected the code — you own the data.
import { NextResponse } from 'next/server';
import { stripe } from '@/prodify-layer/payments/stripe';
import { insforge } from '@/lib/insforge';
import Stripe from 'stripe';

export async function POST(req: Request) {
  const body = await req.text();
  const sig = req.headers.get('stripe-signature');
  if (!sig) {
    return NextResponse.json({ error: 'Missing stripe-signature header' }, { status: 400 });
  }

  let event: Stripe.Event;
  try {
    event = stripe.webhooks.constructEvent(
      body,
      sig,
      process.env.STRIPE_WEBHOOK_SECRET!,
    );
  } catch (err) {
    return NextResponse.json({ error: 'Webhook signature failed' }, { status: 400 });
  }

  // Persist raw event for idempotency / replay
  await insforge.database
    .from('webhook_events')
    .upsert(
      { stripe_event_id: event.id, type: event.type, payload: JSON.stringify(event) },
      { onConflict: 'stripe_event_id' },
    );

  switch (event.type) {
    case 'checkout.session.completed': {
      const session = event.data.object as Stripe.Checkout.Session;

      if (session.metadata?.type === 'credit-purchase') {
        // Add purchased credits to user's DB balance
        const credits = parseInt(session.metadata.credits ?? '0');
        // TODO: look up user by customer ID and increment credits_remaining
        console.log('Credit purchase complete, add', credits, 'credits for customer:', session.customer);
        break;
      }

      // For subscriptions: provision access in DB
      console.log('Subscription checkout complete:', session.id);
      // TODO: update subscription status to 'active' in DB
      break;
    }
    case 'customer.subscription.updated': {
      const sub = event.data.object as Stripe.Subscription;
      // TODO: sync subscription status and period_end to DB
      console.log('Subscription updated:', sub.id, sub.status);
      break;
    }
    case 'customer.subscription.deleted': {
      const sub = event.data.object as Stripe.Subscription;
      // TODO: revoke access in DB (set status to 'cancelled')
      console.log('Subscription cancelled:', sub.id);
      break;
    }
    case 'invoice.payment_failed': {
      const invoice = event.data.object as Stripe.Invoice;
      // TODO: send payment failed email, set subscription to 'past_due' in DB
      console.log('Payment failed for customer:', invoice.customer);
      break;
    }
  }

  return NextResponse.json({ received: true });
}
`;

const portalRoute = `// prodify-layer/routes/api/portal/route.ts
// Drop into app/api/portal/route.ts — Stripe Customer Portal redirect
import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/prodify-layer/auth/[...nextauth]';
import { stripe } from '@/prodify-layer/payments/stripe';

export async function POST(req: Request) {
  const session = await getServerSession(authOptions);
  if (!session?.user?.id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const origin = process.env.NEXT_PUBLIC_APP_URL ?? 'http://localhost:3000';

  // TODO: look up Stripe customerId from DB using session.user.id
  const customerId = 'cus_placeholder';

  const portalSession = await stripe.billingPortal.sessions.create({
    customer: customerId,
    return_url: \`\${origin}/dashboard\`,
  });

  return NextResponse.json({ url: portalSession.url });
}
`;

// ── Public API ────────────────────────────────────────────────────────────────

export function buildPaymentsFiles(
  pricingModel: PricingModel,
  billingInterval: BillingInterval,
  onboardingFlow: OnboardingFlow,
): FileEntry[] {
  const stripeContent =
    pricingModel === 'credits'  ? creditsStripe() :
    pricingModel === 'one-time' ? oneTimeStripe() :
    pricingModel === 'hybrid'   ? hybridStripe(billingInterval, onboardingFlow) :
    pricingModel === 'usage'    ? usageStripe(onboardingFlow) :
    pricingModel === 'per-seat' ? perSeatStripe(billingInterval, onboardingFlow) :
                                  flatStripe(billingInterval, onboardingFlow);

  return [
    { relativePath: 'prodify-layer/payments/stripe.ts', content: stripeContent },
    { relativePath: 'prodify-layer/routes/api/checkout/route.ts', content: buildCheckoutRoute(pricingModel, onboardingFlow) },
    { relativePath: 'prodify-layer/routes/api/webhooks/stripe/route.ts', content: webhookRoute },
    { relativePath: 'prodify-layer/routes/api/portal/route.ts', content: portalRoute },
  ];
}
