// ─── README Injector ──────────────────────────────────────────────────────────
// Generates a README-prodify.md explaining what was injected and how to activate it.
import type { FileEntry, ProdifyAnswers } from '../types';

const PRICING_LABELS: Record<string, string> = {
  flat:       'Flat subscription',
  'per-seat': 'Per-seat subscription',
  usage:      'Usage-based (metered)',
  hybrid:     'Hybrid (flat base + usage overages)',
  'one-time': 'One-time payment',
  credits:    'Credits / token pool (DB ledger)',
};

const ONBOARDING_LABELS: Record<string, string> = {
  'pay-upfront':  'Pay upfront — no trial',
  'trial-card':   'Free trial (card required)',
  'trial-no-card':'Free trial (no card)',
  freemium:       'Freemium (free tier with limits)',
};

const DEPLOY_LABELS: Record<string, string> = {
  vercel:  'Vercel',
  railway: 'Railway',
  fly:     'Fly.io',
  aws:     'AWS Lightsail',
  none:    'None (build-only CI)',
};

const COMPLIANCE_LABELS: Record<string, string> = {
  global:   'Global (Terms of Service only)',
  'eu-gdpr':'EU / GDPR (Cookie banner + Privacy policy)',
  us:       'US / CCPA (CCPA notice)',
};

export function buildReadmeFile(answers: ProdifyAnswers): FileEntry[] {
  const today = new Date().toISOString().split('T')[0];

  const trialNote = (answers.onboardingFlow === 'trial-card' || answers.onboardingFlow === 'trial-no-card')
    ? `  **Trial length:** ${answers.trialDays ?? 14} days`
    : answers.onboardingFlow === 'freemium'
    ? `  **Free tier limit:** ${answers.freeLimit ?? 'see free_usage table'}`
    : '';

  const annualNote = answers.billingInterval === 'annual'
    ? '  **Annual billing:** enabled — set both STRIPE_MONTHLY_PRICE_ID and STRIPE_ANNUAL_PRICE_ID'
    : '';

  const complianceFiles = answers.complianceRegion === 'eu-gdpr'
    ? ['cookie-banner.tsx', 'privacy-policy.md', 'terms.md']
    : answers.complianceRegion === 'us'
    ? ['ccpa-notice.md', 'terms.md']
    : ['terms.md'];

  const content = `# Prodify Infrastructure Layer — ${answers.appName}

> Auto-generated by [Prodify](https://github.com/maitreyee/prodify) on ${today}

---

## ⚠️ Trust & data separation

> **Prodify never sees your Stripe keys or your customers' payment data.**
> We inject the code. You paste your own keys. Your Stripe account handles
> all payments. Your customers' payment data never flows through Prodify.

---

## What was injected

| Layer | Configuration | Location |
|-------|---------------|----------|
| Auth | NextAuth.js (${answers.authMethods.join(', ')}) | \`prodify-layer/auth/\` |
| Payments | ${PRICING_LABELS[answers.pricingModel] ?? answers.pricingModel} | \`prodify-layer/payments/\` |
| Onboarding | ${ONBOARDING_LABELS[answers.onboardingFlow] ?? answers.onboardingFlow} | checkout session |
| Database | InsForge (${answers.userType}) | \`prodify-layer/db/\` |
| Email | Resend (3 templates) | \`prodify-layer/email/\` |
| CI/CD | ${DEPLOY_LABELS[answers.deployTarget] ?? answers.deployTarget} | \`.github/workflows/\` |
| Compliance | ${COMPLIANCE_LABELS[answers.complianceRegion] ?? answers.complianceRegion} | \`prodify-layer/compliance/\` |
| API Routes | Next.js App Router | \`prodify-layer/routes/api/\` |
| Environment | .env.example | \`.env.example\` |

${trialNote}
${annualNote}

**Stack detected:** ${answers.stack}

---

## Activation checklist

- [ ] **Copy .env.example** → \`.env.local\` and fill in all values
- [ ] **Install dependencies:**
  \`\`\`bash
  npm install next-auth @insforge/sdk stripe resend @react-email/components
  \`\`\`
- [ ] **Run the InsForge schema** — open your InsForge project SQL editor and run:
  \`\`\`bash
  cat prodify-layer/db/schema.sql
  \`\`\`
- [ ] **Copy the InsForge client** into \`lib/insforge.ts\`:
  \`\`\`bash
  cp prodify-layer/db/insforge.ts lib/insforge.ts
  \`\`\`
- [ ] **Mount the API routes** — copy from \`prodify-layer/routes/api/\` into \`app/api/\`
- [ ] **Set up Stripe webhook** (local dev):
  \`\`\`bash
  stripe listen --forward-to localhost:3000/api/webhooks/stripe
  \`\`\`
- [ ] **Configure OAuth apps** — see .env.example for setup links
- [ ] **Create Stripe prices** — see .env.example for which price IDs you need
${answers.complianceRegion === 'eu-gdpr'
  ? '- [ ] **Mount the cookie banner** — add `<CookieBanner />` to your root `app/layout.tsx`\n- [ ] **Fill in the privacy policy** — edit `prodify-layer/compliance/privacy-policy.md`'
  : answers.complianceRegion === 'us'
  ? '- [ ] **Complete the CCPA notice** — edit `prodify-layer/compliance/ccpa-notice.md` with your company details'
  : ''}
${answers.deployTarget !== 'none'
  ? `- [ ] **Add CI secrets** — see \`.env.example\` for required GitHub Actions secrets for ${DEPLOY_LABELS[answers.deployTarget]}`
  : ''}

---

## File tree

\`\`\`
prodify-layer/
├── auth/
│   └── [...nextauth].ts
├── payments/
│   └── stripe.ts
├── email/
│   ├── client.ts
│   └── templates/
│       ├── welcome.tsx
│       ├── trial-ending.tsx
│       └── receipt.tsx
├── compliance/
${complianceFiles.map(f => `│   └── ${f}`).join('\n')}
├── routes/
│   └── api/
│       ├── auth/[...nextauth]/route.ts
│       ├── checkout/route.ts
│       ├── webhooks/stripe/route.ts
│       └── portal/route.ts
├── db/
│   ├── insforge.ts
│   └── schema.sql
└── README-prodify.md
\`\`\`
.github/
└── workflows/
    └── deploy.yml
`;

  return [{ relativePath: 'prodify-layer/README-prodify.md', content }];
}
