// ─── README Injector ──────────────────────────────────────────────────────────
// Generates a README-prodify.md explaining what was injected and how to activate it.
import type { FileEntry, ProdifyAnswers } from '../types';

export function buildReadmeFile(answers: ProdifyAnswers): FileEntry[] {
  const today = new Date().toISOString().split('T')[0];

  const content = `# Prodify Infrastructure Layer

> Auto-generated by [Prodify](https://github.com/maitreyee/prodify) on ${today}

## What was injected

| Layer | Model | Location |
|-------|-------|----------|
| Auth | NextAuth.js (${answers.userType}) | \`prodify-layer/auth/\` |
| Payments | Stripe (${answers.pricingModel}) | \`prodify-layer/payments/\` |
| Database | Prisma schema (${answers.userType}) | \`prodify-layer/db/schema.prisma\` |
| API Routes | Next.js App Router | \`prodify-layer/routes/api/\` |
| Environment | .env.example | \`.env.example\` |

**Stack detected:** ${answers.stack}
**Pricing model:** ${answers.pricingModel}
**User type:** ${answers.userType}

---

## Activation checklist

- [ ] **Copy .env.example** → \`.env.local\` and fill in all values
- [ ] **Install dependencies:**
  \`\`\`bash
  npm install next-auth @auth/prisma-adapter stripe @prisma/client prisma
  \`\`\`
- [ ] **Copy the Prisma schema:**
  \`\`\`bash
  cp prodify-layer/db/schema.prisma prisma/schema.prisma
  npx prisma migrate dev --name init
  \`\`\`
- [ ] **Mount the API routes** — copy from \`prodify-layer/routes/api/\` into \`app/api/\`
- [ ] **Create a \`lib/prisma.ts\`** singleton:
  \`\`\`typescript
  import { PrismaClient } from '@prisma/client';
  const globalForPrisma = global as unknown as { prisma: PrismaClient };
  export const prisma = globalForPrisma.prisma ?? new PrismaClient();
  if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = prisma;
  \`\`\`
- [ ] **Set up Stripe webhook** (local dev):
  \`\`\`bash
  stripe listen --forward-to localhost:3000/api/webhooks/stripe
  \`\`\`
- [ ] **Configure OAuth apps** — see .env.example for links

---

## File tree

\`\`\`
prodify-layer/
├── auth/
│   └── [...nextauth].ts
├── payments/
│   └── stripe.ts
├── routes/
│   └── api/
│       ├── auth/[...nextauth]/route.ts
│       ├── checkout/route.ts
│       ├── webhooks/stripe/route.ts
│       └── portal/route.ts
├── db/
│   └── schema.prisma
└── README-prodify.md
\`\`\`
`;

  return [{ relativePath: 'prodify-layer/README-prodify.md', content }];
}
