// ─── UI Injector ──────────────────────────────────────────────────────────────
// Generates ready-to-use React UI components into prodify-layer/ui/.
// Each component has a plain JSX variant and a shadcn/ui (Radix + Tailwind) variant.
// Only relevant components are generated based on pricing model and auth methods.
import type { FileEntry, ProdifyAnswers, AuthMethod, UILibrary, PricingModel, OnboardingFlow } from '../types';

// ── Sign-In Button ────────────────────────────────────────────────────────────

function signInButtonPlain(authMethods: AuthMethod[]): string {
  const buttons = authMethods
    .filter((m) => ['google', 'github', 'magic-link', 'email-pass'].includes(m))
    .map((m) => {
      if (m === 'google') {
        return `      <button
        onClick={() => signIn('google', { callbackUrl: '/' })}
        style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '10px 20px',
                 border: '1px solid #e0e0e0', borderRadius: 8, background: '#fff',
                 cursor: 'pointer', fontSize: 14, fontWeight: 500 }}
      >
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none">
          <path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" fill="#4285F4"/>
          <path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" fill="#34A853"/>
          <path d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l3.66-2.84z" fill="#FBBC05"/>
          <path d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" fill="#EA4335"/>
        </svg>
        Sign in with Google
      </button>`;
      }
      if (m === 'github') {
        return `      <button
        onClick={() => signIn('github', { callbackUrl: '/' })}
        style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '10px 20px',
                 border: '1px solid #e0e0e0', borderRadius: 8, background: '#24292e',
                 color: '#fff', cursor: 'pointer', fontSize: 14, fontWeight: 500 }}
      >
        <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor">
          <path d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385.6.105.825-.255.825-.57 0-.285-.015-1.23-.015-2.235-3.015.555-3.795-.735-4.035-1.41-.135-.345-.72-1.41-1.23-1.695-.42-.225-1.02-.78-.015-.795.945-.015 1.62.87 1.845 1.23 1.08 1.815 2.805 1.305 3.495.99.105-.78.42-1.305.765-1.605-2.67-.3-5.46-1.335-5.46-5.925 0-1.305.465-2.385 1.23-3.225-.12-.3-.54-1.53.12-3.18 0 0 1.005-.315 3.3 1.23.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23.66 1.65.24 2.88.12 3.18.765.84 1.23 1.905 1.23 3.225 0 4.605-2.805 5.625-5.475 5.925.435.375.81 1.095.81 2.22 0 1.605-.015 2.895-.015 3.3 0 .315.225.69.825.57A12.02 12.02 0 0 0 24 12c0-6.63-5.37-12-12-12z"/>
        </svg>
        Sign in with GitHub
      </button>`;
      }
      if (m === 'magic-link') {
        return `      <MagicLinkForm />`;
      }
      if (m === 'email-pass') {
        return `      <EmailPasswordForm />`;
      }
      return '';
    })
    .filter(Boolean)
    .join('\n');

  return `// prodify-layer/ui/auth/sign-in-button.tsx
// Generated by Prodify — mount this wherever you need login buttons.
// Plain JSX variant — no extra dependencies required.
'use client';
import { signIn } from 'next-auth/react';

${authMethods.includes('magic-link') ? `function MagicLinkForm() {
  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const form = e.currentTarget;
    const email = (form.elements.namedItem('email') as HTMLInputElement).value;
    await signIn('email', { email, callbackUrl: '/' });
  };
  return (
    <form onSubmit={handleSubmit} style={{ display: 'flex', gap: 8, flexDirection: 'column' }}>
      <input name="email" type="email" placeholder="your@email.com"
        style={{ padding: '10px 12px', border: '1px solid #e0e0e0', borderRadius: 8, fontSize: 14 }} />
      <button type="submit"
        style={{ padding: '10px 20px', background: '#111', color: '#fff',
                 border: 'none', borderRadius: 8, cursor: 'pointer', fontSize: 14 }}>
        Send magic link
      </button>
    </form>
  );
}` : ''}

export function SignInButton() {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
${buttons}
    </div>
  );
}
`;
}

function signInButtonShadcn(authMethods: AuthMethod[]): string {
  const buttons = authMethods
    .filter((m) => ['google', 'github', 'magic-link', 'email-pass'].includes(m))
    .map((m) => {
      if (m === 'google') return `      <Button variant="outline" className="w-full" onClick={() => signIn('google', { callbackUrl: '/' })}>Sign in with Google</Button>`;
      if (m === 'github') return `      <Button className="w-full bg-[#24292e] text-white" onClick={() => signIn('github', { callbackUrl: '/' })}>Sign in with GitHub</Button>`;
      if (m === 'magic-link') return `      <MagicLinkForm />`;
      if (m === 'email-pass') return `      <EmailPasswordForm />`;
      return '';
    })
    .filter(Boolean)
    .join('\n');

  return `// prodify-layer/ui/auth/sign-in-button.tsx
// Generated by Prodify — mount this wherever you need login buttons.
// shadcn/ui variant — requires @radix-ui/react-slot and class-variance-authority.
'use client';
import { signIn } from 'next-auth/react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';

${authMethods.includes('magic-link') ? `function MagicLinkForm() {
  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const form = e.currentTarget;
    const email = (form.elements.namedItem('email') as HTMLInputElement).value;
    await signIn('email', { email, callbackUrl: '/' });
  };
  return (
    <form onSubmit={handleSubmit} className="flex flex-col gap-3">
      <Input name="email" type="email" placeholder="your@email.com" />
      <Button type="submit" className="w-full">Send magic link</Button>
    </form>
  );
}` : ''}

export function SignInButton() {
  return (
    <div className="flex flex-col gap-3">
${buttons}
    </div>
  );
}
`;
}

// ── Sign-Out Button ───────────────────────────────────────────────────────────

function signOutButtonPlain(): string {
  return `// prodify-layer/ui/auth/sign-out-button.tsx
// Generated by Prodify
'use client';
import { signOut } from 'next-auth/react';

export function SignOutButton() {
  return (
    <button
      onClick={() => signOut({ callbackUrl: '/' })}
      style={{ padding: '8px 16px', border: '1px solid #e0e0e0', borderRadius: 8,
               background: 'transparent', cursor: 'pointer', fontSize: 14 }}
    >
      Sign out
    </button>
  );
}
`;
}

function signOutButtonShadcn(): string {
  return `// prodify-layer/ui/auth/sign-out-button.tsx
// Generated by Prodify — shadcn/ui variant
'use client';
import { signOut } from 'next-auth/react';
import { Button } from '@/components/ui/button';

export function SignOutButton() {
  return (
    <Button variant="ghost" onClick={() => signOut({ callbackUrl: '/' })}>
      Sign out
    </Button>
  );
}
`;
}

// ── Billing Portal Button ─────────────────────────────────────────────────────

function billingPortalButtonPlain(): string {
  return `// prodify-layer/ui/pricing/billing-portal-button.tsx
// Generated by Prodify
// Mount in your dashboard wherever the user manages their subscription.
'use client';
import { useState } from 'react';

export function BillingPortalButton() {
  const [loading, setLoading] = useState(false);

  const handleClick = async () => {
    setLoading(true);
    try {
      const res = await fetch('/api/portal', { method: 'POST' });
      const data = await res.json() as { url?: string; error?: string };
      if (data.url) {
        window.location.href = data.url;
      } else {
        console.error('Portal error:', data.error);
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <button
      onClick={handleClick}
      disabled={loading}
      style={{ padding: '10px 20px', background: '#111', color: '#fff',
               border: 'none', borderRadius: 8, cursor: loading ? 'not-allowed' : 'pointer',
               fontSize: 14, opacity: loading ? 0.7 : 1 }}
    >
      {loading ? 'Loading…' : 'Manage subscription'}
    </button>
  );
}
`;
}

function billingPortalButtonShadcn(): string {
  return `// prodify-layer/ui/pricing/billing-portal-button.tsx
// Generated by Prodify — shadcn/ui variant
'use client';
import { useState } from 'react';
import { Button } from '@/components/ui/button';

export function BillingPortalButton() {
  const [loading, setLoading] = useState(false);

  const handleClick = async () => {
    setLoading(true);
    try {
      const res = await fetch('/api/portal', { method: 'POST' });
      const data = await res.json() as { url?: string; error?: string };
      if (data.url) window.location.href = data.url;
    } finally {
      setLoading(false);
    }
  };

  return (
    <Button onClick={handleClick} disabled={loading} variant="outline">
      {loading ? 'Loading…' : 'Manage subscription'}
    </Button>
  );
}
`;
}

// ── Pricing Page ──────────────────────────────────────────────────────────────

function pricingPagePlain(pricingModel: PricingModel): string {
  const modelLabel = {
    flat: '/month',
    'per-seat': '/user/month',
    usage: ' — pay as you go',
    hybrid: '/month + usage',
    'one-time': ' one-time',
    credits: ' per credit pack',
  }[pricingModel];

  return `// prodify-layer/ui/pricing/pricing-page.tsx
// Generated by Prodify — pricing: ${pricingModel}
// Replace the plan details with your actual prices.
'use client';
import { useState } from 'react';

const plans = [
  {
    name: 'Starter',
    price: '$9',
    interval: '${modelLabel}',
    features: ['Up to 3 projects', '1,000 API calls/month', 'Email support'],
    cta: 'Get started',
    highlighted: false,
  },
  {
    name: 'Pro',
    price: '$29',
    interval: '${modelLabel}',
    features: ['Unlimited projects', '50,000 API calls/month', 'Priority support', 'Team members'],
    cta: 'Start free trial',
    highlighted: true,
  },
  {
    name: 'Enterprise',
    price: 'Custom',
    interval: '',
    features: ['Custom limits', 'Dedicated support', 'SSO/SAML', 'SLA'],
    cta: 'Contact us',
    highlighted: false,
  },
];

export default function PricingPage() {
  const [loading, setLoading] = useState<string | null>(null);

  const handleCheckout = async (planName: string) => {
    setLoading(planName);
    try {
      const res = await fetch('/api/checkout', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ plan: planName }),
      });
      const data = await res.json() as { url?: string };
      if (data.url) window.location.href = data.url;
    } finally {
      setLoading(null);
    }
  };

  return (
    <div style={{ maxWidth: 960, margin: '0 auto', padding: '60px 24px', textAlign: 'center' }}>
      <h1 style={{ fontSize: 40, fontWeight: 700, marginBottom: 12 }}>Simple pricing</h1>
      <p style={{ color: '#666', marginBottom: 48 }}>No hidden fees. Cancel anytime.</p>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: 24 }}>
        {plans.map((plan) => (
          <div
            key={plan.name}
            style={{
              border: plan.highlighted ? '2px solid #111' : '1px solid #e0e0e0',
              borderRadius: 16,
              padding: 32,
              background: plan.highlighted ? '#111' : '#fff',
              color: plan.highlighted ? '#fff' : '#111',
            }}
          >
            <h2 style={{ fontSize: 20, fontWeight: 600, marginBottom: 8 }}>{plan.name}</h2>
            <div style={{ fontSize: 36, fontWeight: 700, marginBottom: 4 }}>{plan.price}</div>
            <div style={{ fontSize: 14, opacity: 0.6, marginBottom: 24 }}>{plan.interval}</div>
            <ul style={{ textAlign: 'left', marginBottom: 24, padding: 0, listStyle: 'none' }}>
              {plan.features.map((f) => (
                <li key={f} style={{ marginBottom: 8, fontSize: 14 }}>✓ {f}</li>
              ))}
            </ul>
            <button
              onClick={() => handleCheckout(plan.name)}
              disabled={loading === plan.name}
              style={{
                width: '100%', padding: '12px 20px',
                background: plan.highlighted ? '#fff' : '#111',
                color: plan.highlighted ? '#111' : '#fff',
                border: 'none', borderRadius: 8, cursor: 'pointer',
                fontSize: 14, fontWeight: 600, opacity: loading === plan.name ? 0.7 : 1,
              }}
            >
              {loading === plan.name ? 'Loading…' : plan.cta}
            </button>
          </div>
        ))}
      </div>
    </div>
  );
}
`;
}

// ── Credit Balance ────────────────────────────────────────────────────────────

function creditBalancePlain(): string {
  return `// prodify-layer/ui/credits/credit-balance.tsx
// Generated by Prodify — credits pricing model
// Shows the user's current credit balance with a top-up button.
'use client';
import { useEffect, useState } from 'react';

interface BalanceData {
  balance: number;
}

export function CreditBalance() {
  const [balance, setBalance] = useState<number | null>(null);

  useEffect(() => {
    fetch('/api/credits/balance')
      .then((r) => r.json())
      .then((d: BalanceData) => setBalance(d.balance))
      .catch(console.error);
  }, []);

  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
      <span style={{ fontSize: 14, color: '#666' }}>Credits:</span>
      <span style={{ fontSize: 16, fontWeight: 700 }}>
        {balance === null ? '…' : balance.toLocaleString()}
      </span>
      <a
        href="/pricing"
        style={{ fontSize: 13, color: '#2563eb', textDecoration: 'underline' }}
      >
        Top up
      </a>
    </div>
  );
}
`;
}

// ── Freemium Usage Meter ──────────────────────────────────────────────────────

function usageMeterPlain(): string {
  return `// prodify-layer/ui/freemium/usage-meter.tsx
// Generated by Prodify — freemium onboarding model
// Shows how much of the free allowance the user has consumed.
'use client';
import { useEffect, useState } from 'react';

interface UsageData {
  used: number;
  limit: number;
  label: string;   // e.g. "API calls this month"
}

export function UsageMeter() {
  const [usage, setUsage] = useState<UsageData | null>(null);

  useEffect(() => {
    fetch('/api/usage')
      .then((r) => r.json())
      .then((d: UsageData) => setUsage(d))
      .catch(console.error);
  }, []);

  if (!usage) return null;

  const pct = Math.min((usage.used / usage.limit) * 100, 100);
  const isNearLimit = pct >= 80;

  return (
    <div style={{ maxWidth: 320 }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 6, fontSize: 13 }}>
        <span style={{ color: '#666' }}>{usage.label}</span>
        <span style={{ fontWeight: 600, color: isNearLimit ? '#dc2626' : '#111' }}>
          {usage.used.toLocaleString()} / {usage.limit.toLocaleString()}
        </span>
      </div>
      <div style={{ height: 6, background: '#e5e7eb', borderRadius: 99 }}>
        <div
          style={{
            height: '100%',
            width: \`\${pct}%\`,
            background: isNearLimit ? '#dc2626' : '#2563eb',
            borderRadius: 99,
            transition: 'width 0.3s ease',
          }}
        />
      </div>
      {isNearLimit && (
        <p style={{ marginTop: 8, fontSize: 12, color: '#dc2626' }}>
          You're close to your free limit.{' '}
          <a href="/pricing" style={{ textDecoration: 'underline' }}>Upgrade to Pro →</a>
        </p>
      )}
    </div>
  );
}
`;
}

// ── Main builder ──────────────────────────────────────────────────────────────

export function buildUiFiles(answers: ProdifyAnswers): FileEntry[] {
  if (!answers.injectUi) return [];

  const lib: UILibrary = answers.uiLibrary ?? 'plain';
  const files: FileEntry[] = [];

  // Auth components
  files.push({
    relativePath: 'prodify-layer/ui/auth/sign-in-button.tsx',
    content: lib === 'shadcn'
      ? signInButtonShadcn(answers.authMethods)
      : signInButtonPlain(answers.authMethods),
  });

  files.push({
    relativePath: 'prodify-layer/ui/auth/sign-out-button.tsx',
    content: lib === 'shadcn' ? signOutButtonShadcn() : signOutButtonPlain(),
  });

  // Pricing components
  files.push({
    relativePath: 'prodify-layer/ui/pricing/billing-portal-button.tsx',
    content: lib === 'shadcn' ? billingPortalButtonShadcn() : billingPortalButtonPlain(),
  });

  files.push({
    relativePath: 'prodify-layer/ui/pricing/pricing-page.tsx',
    content: pricingPagePlain(answers.pricingModel), // same for both libs for now
  });

  // Credits-specific
  if (answers.pricingModel === 'credits') {
    files.push({
      relativePath: 'prodify-layer/ui/credits/credit-balance.tsx',
      content: creditBalancePlain(),
    });
  }

  // Freemium-specific
  if (answers.onboardingFlow === 'freemium') {
    files.push({
      relativePath: 'prodify-layer/ui/freemium/usage-meter.tsx',
      content: usageMeterPlain(),
    });
  }

  return files;
}
